package components

import (
	"starve/internal/ecs"
)

// RegisterCodecs 为玩法组件注册名称 + codec（快照/存档用）。
// 必须在组件第一次被 Add/Query 之前调用（WorldActor 构造时执行）。
// 每个组件的注册调用放在各自的文件里（RegisterX），这里只做统一入口。
func RegisterCodecs(w *ecs.World, debugAOI bool) {
	RegisterPosition(w)
	RegisterMoveable(w)
	RegisterActionState(w)
	RegisterHealth(w)
	RegisterHunger(w)
	RegisterGrowable(w)
	RegisterDead(w)
	RegisterDropSource(w)
	RegisterScenery(w)
	RegisterPlayer(w)
	RegisterOffline(w)
	RegisterWorkable(w)
	RegisterEquipped(w)
	RegisterRespawn(w)
	RegisterWorkstation(w)
	RegisterHauntable(w)
	RegisterCrafting(w)
	RegisterInventory(w)
	RegisterLoot(w)
	RegisterLootable(w)
	RegisterEffects(w)
	RegisterEffectEmitter(w)
	RegisterFan(w)
	RegisterHeatSource(w)
	RegisterFuel(w)
	RegisterCreature(w)
	RegisterAI(w)
	RegisterBehaviorTree(w)
	RegisterWeapon(w)
	RegisterRespawnable(w)
	RegisterDefense(w)
	RegisterAttackable(w)
	RegisterEquip(w)
	RegisterAOI(w, debugAOI)
	RegisterBuilding(w)
	RegisterBlock(w)
	RegisterCollide(w)
	RegisterPushable(w)
	RegisterThrowable(w)
	RegisterThrower(w)
	RegisterThrown(w)
	RegisterExplosive(w)
	RegisterFuseRemaining(w)
	RegisterDebugShape(w)
}
