// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/proto/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemKind 物品/实体类型（稳定 ID）：资源、工具等共用一个枚举。
// 新类型 = 新枚举值 + 模板表条目（样式/颜色/掉落等静态属性在模板表，不在枚举）。
type ItemKind int32

const (
	ItemKind_ITEM_KIND_UNSPECIFIED ItemKind = 0
	// 资源段 1-99
	ItemKind_ITEM_KIND_BERRY ItemKind = 1
	ItemKind_ITEM_KIND_WOOD  ItemKind = 2
	ItemKind_ITEM_KIND_FLINT ItemKind = 3
	// 工具段 100-199
	ItemKind_ITEM_KIND_AXE     ItemKind = 100 // 工具（砍伐）
	ItemKind_ITEM_KIND_PICKAXE ItemKind = 101 // 工具（挖掘）
)

// Enum value maps for ItemKind.
var (
	ItemKind_name = map[int32]string{
		0:   "ITEM_KIND_UNSPECIFIED",
		1:   "ITEM_KIND_BERRY",
		2:   "ITEM_KIND_WOOD",
		3:   "ITEM_KIND_FLINT",
		100: "ITEM_KIND_AXE",
		101: "ITEM_KIND_PICKAXE",
	}
	ItemKind_value = map[string]int32{
		"ITEM_KIND_UNSPECIFIED": 0,
		"ITEM_KIND_BERRY":       1,
		"ITEM_KIND_WOOD":        2,
		"ITEM_KIND_FLINT":       3,
		"ITEM_KIND_AXE":         100,
		"ITEM_KIND_PICKAXE":     101,
	}
)

func (x ItemKind) Enum() *ItemKind {
	p := new(ItemKind)
	*p = x
	return p
}

func (x ItemKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[0].Descriptor()
}

func (ItemKind) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[0]
}

func (x ItemKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemKind.Descriptor instead.
func (ItemKind) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{0}
}

// WorkAction 可交互动作（目标声明能被什么动作处理，工具声明做什么动作）。
type WorkAction int32

const (
	WorkAction_WORK_ACTION_UNSPECIFIED WorkAction = 0
	WorkAction_WORK_ACTION_CHOP        WorkAction = 1 // 砍伐（树）
	WorkAction_WORK_ACTION_MINE        WorkAction = 2 // 挖掘（矿）
	WorkAction_WORK_ACTION_PICK        WorkAction = 3 // 采集（浆果丛）
)

// Enum value maps for WorkAction.
var (
	WorkAction_name = map[int32]string{
		0: "WORK_ACTION_UNSPECIFIED",
		1: "WORK_ACTION_CHOP",
		2: "WORK_ACTION_MINE",
		3: "WORK_ACTION_PICK",
	}
	WorkAction_value = map[string]int32{
		"WORK_ACTION_UNSPECIFIED": 0,
		"WORK_ACTION_CHOP":        1,
		"WORK_ACTION_MINE":        2,
		"WORK_ACTION_PICK":        3,
	}
)

func (x WorkAction) Enum() *WorkAction {
	p := new(WorkAction)
	*p = x
	return p
}

func (x WorkAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[1].Descriptor()
}

func (WorkAction) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[1]
}

func (x WorkAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkAction.Descriptor instead.
func (WorkAction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{1}
}

// WorkstationType 工作站类型（稳定 ID）。
type WorkstationType int32

const (
	WorkstationType_WORKSTATION_TYPE_UNSPECIFIED WorkstationType = 0
	WorkstationType_WORKSTATION_TYPE_CAMPFIRE    WorkstationType = 1 // 火堆
	WorkstationType_WORKSTATION_TYPE_WORKBENCH   WorkstationType = 2 // 工作台
)

// Enum value maps for WorkstationType.
var (
	WorkstationType_name = map[int32]string{
		0: "WORKSTATION_TYPE_UNSPECIFIED",
		1: "WORKSTATION_TYPE_CAMPFIRE",
		2: "WORKSTATION_TYPE_WORKBENCH",
	}
	WorkstationType_value = map[string]int32{
		"WORKSTATION_TYPE_UNSPECIFIED": 0,
		"WORKSTATION_TYPE_CAMPFIRE":    1,
		"WORKSTATION_TYPE_WORKBENCH":   2,
	}
)

func (x WorkstationType) Enum() *WorkstationType {
	p := new(WorkstationType)
	*p = x
	return p
}

func (x WorkstationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkstationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[2].Descriptor()
}

func (WorkstationType) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[2]
}

func (x WorkstationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkstationType.Descriptor instead.
func (WorkstationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{2}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cur           int32                  `protobuf:"varint,1,opt,name=cur,proto3" json:"cur,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *Health) GetCur() int32 {
	if x != nil {
		return x.Cur
	}
	return 0
}

func (x *Health) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Hunger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Rate          int32                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"` // 每 tick 消耗速率（0 表示用世界默认）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hunger) Reset() {
	*x = Hunger{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunger) ProtoMessage() {}

func (x *Hunger) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunger.ProtoReflect.Descriptor instead.
func (*Hunger) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *Hunger) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Hunger) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Growable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         int32                  `protobuf:"varint,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Ticks         int32                  `protobuf:"varint,2,opt,name=ticks,proto3" json:"ticks,omitempty"` // 距上次生长经过的 tick 数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Growable) Reset() {
	*x = Growable{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Growable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Growable) ProtoMessage() {}

func (x *Growable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Growable.ProtoReflect.Descriptor instead.
func (*Growable) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *Growable) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Growable) GetTicks() int32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

// Dead 死亡标记：实体死后保留在世界上（尸体/幽灵状态），由后续系统处理。
type Dead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	SinceTick     int64                  `protobuf:"varint,2,opt,name=since_tick,json=sinceTick,proto3" json:"since_tick,omitempty"` // 死亡起始世界 tick（尸体清理用；旧档为 0 时世界自动补盖）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dead) Reset() {
	*x = Dead{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dead) ProtoMessage() {}

func (x *Dead) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dead.ProtoReflect.Descriptor instead.
func (*Dead) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *Dead) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Dead) GetSinceTick() int64 {
	if x != nil {
		return x.SinceTick
	}
	return 0
}

// Player 玩家标记：把 UID（账号）挂到实体上，快照携带，加载时重建所有权表。
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *Player) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Offline 离线标记：断线后实体保留在世界上（断线保留 N 分钟），重连复用。
type Offline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceTick     int64                  `protobuf:"varint,1,opt,name=since_tick,json=sinceTick,proto3" json:"since_tick,omitempty"` // 离线起始世界 tick（用于超时清理）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offline) Reset() {
	*x = Offline{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline) ProtoMessage() {}

func (x *Offline) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline.ProtoReflect.Descriptor instead.
func (*Offline) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{6}
}

func (x *Offline) GetSinceTick() int64 {
	if x != nil {
		return x.SinceTick
	}
	return 0
}

// Workable 可交互环境物（树/矿/浆果丛）：动作 + 剩余工作量。
// 用 WorkLeft 表达耐久（不用 Combat Health）：砍伐/挖掘/采集走工作量，
// 生物才用 Health——两条伤害通道互不干扰。
type Workable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`       // 实体类型（掉落/模板查找用）
	Action        WorkAction             `protobuf:"varint,2,opt,name=action,proto3,enum=starve.game.v1.WorkAction" json:"action,omitempty"` // 能被什么动作处理
	WorkLeft      int32                  `protobuf:"varint,3,opt,name=work_left,json=workLeft,proto3" json:"work_left,omitempty"`
	MaxWork       int32                  `protobuf:"varint,4,opt,name=max_work,json=maxWork,proto3" json:"max_work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workable) Reset() {
	*x = Workable{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workable) ProtoMessage() {}

func (x *Workable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workable.ProtoReflect.Descriptor instead.
func (*Workable) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{7}
}

func (x *Workable) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *Workable) GetAction() WorkAction {
	if x != nil {
		return x.Action
	}
	return WorkAction_WORK_ACTION_UNSPECIFIED
}

func (x *Workable) GetWorkLeft() int32 {
	if x != nil {
		return x.WorkLeft
	}
	return 0
}

func (x *Workable) GetMaxWork() int32 {
	if x != nil {
		return x.MaxWork
	}
	return 0
}

// Equipped 玩家当前手持的工具（kind=0 表示徒手）。
type Equipped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Equipped) Reset() {
	*x = Equipped{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equipped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equipped) ProtoMessage() {}

func (x *Equipped) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equipped.ProtoReflect.Descriptor instead.
func (*Equipped) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{8}
}

func (x *Equipped) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

// Respawn 重生标记：有该组件的环境物在耗尽后会自动恢复（如浆果丛重新长出）。
type Respawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticks         int64                  `protobuf:"varint,1,opt,name=ticks,proto3" json:"ticks,omitempty"` // 剩余倒计时（tick）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respawn) Reset() {
	*x = Respawn{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respawn) ProtoMessage() {}

func (x *Respawn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respawn.ProtoReflect.Descriptor instead.
func (*Respawn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{9}
}

func (x *Respawn) GetTicks() int64 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

// Workstation 工作站标记：某些配方要求玩家附近有指定类型的工作站。
type Workstation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkstationType        `protobuf:"varint,1,opt,name=type,proto3,enum=starve.game.v1.WorkstationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workstation) Reset() {
	*x = Workstation{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workstation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workstation) ProtoMessage() {}

func (x *Workstation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workstation.ProtoReflect.Descriptor instead.
func (*Workstation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{10}
}

func (x *Workstation) GetType() WorkstationType {
	if x != nil {
		return x.Type
	}
	return WorkstationType_WORKSTATION_TYPE_UNSPECIFIED
}

// Crafting 制作中的状态（挂在玩家身上）：配方 + 剩余 tick。
type Crafting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	TicksLeft     int64                  `protobuf:"varint,2,opt,name=ticks_left,json=ticksLeft,proto3" json:"ticks_left,omitempty"`
	Ingredients   []*ItemStack           `protobuf:"bytes,3,rep,name=ingredients,proto3" json:"ingredients,omitempty"` // 打断退款用（craft 开始时从配方拷贝）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Crafting) Reset() {
	*x = Crafting{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Crafting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crafting) ProtoMessage() {}

func (x *Crafting) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crafting.ProtoReflect.Descriptor instead.
func (*Crafting) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{11}
}

func (x *Crafting) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *Crafting) GetTicksLeft() int64 {
	if x != nil {
		return x.TicksLeft
	}
	return 0
}

func (x *Crafting) GetIngredients() []*ItemStack {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type ToolConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        WorkAction             `protobuf:"varint,1,opt,name=action,proto3,enum=starve.game.v1.WorkAction" json:"action,omitempty"`
	Efficiency    int32                  `protobuf:"varint,2,opt,name=efficiency,proto3" json:"efficiency,omitempty"`
	Durability    int32                  `protobuf:"varint,3,opt,name=durability,proto3" json:"durability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolConfig) Reset() {
	*x = ToolConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolConfig) ProtoMessage() {}

func (x *ToolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolConfig.ProtoReflect.Descriptor instead.
func (*ToolConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{12}
}

func (x *ToolConfig) GetAction() WorkAction {
	if x != nil {
		return x.Action
	}
	return WorkAction_WORK_ACTION_UNSPECIFIED
}

func (x *ToolConfig) GetEfficiency() int32 {
	if x != nil {
		return x.Efficiency
	}
	return 0
}

func (x *ToolConfig) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

type UseEffectConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hunger        int32                  `protobuf:"varint,1,opt,name=hunger,proto3" json:"hunger,omitempty"`
	Health        int32                  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseEffectConfig) Reset() {
	*x = UseEffectConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseEffectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseEffectConfig) ProtoMessage() {}

func (x *UseEffectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseEffectConfig.ProtoReflect.Descriptor instead.
func (*UseEffectConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{13}
}

func (x *UseEffectConfig) GetHunger() int32 {
	if x != nil {
		return x.Hunger
	}
	return 0
}

func (x *UseEffectConfig) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type DropConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropConfig) Reset() {
	*x = DropConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropConfig) ProtoMessage() {}

func (x *DropConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropConfig.ProtoReflect.Descriptor instead.
func (*DropConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{14}
}

func (x *DropConfig) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *DropConfig) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TemplateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	StackSize     int32                  `protobuf:"varint,4,opt,name=stack_size,json=stackSize,proto3" json:"stack_size,omitempty"`
	RespawnTicks  int32                  `protobuf:"varint,5,opt,name=respawn_ticks,json=respawnTicks,proto3" json:"respawn_ticks,omitempty"`
	Tool          *ToolConfig            `protobuf:"bytes,6,opt,name=tool,proto3" json:"tool,omitempty"`
	UseEffect     *UseEffectConfig       `protobuf:"bytes,7,opt,name=use_effect,json=useEffect,proto3" json:"use_effect,omitempty"`
	DropTable     []*DropConfig          `protobuf:"bytes,8,rep,name=drop_table,json=dropTable,proto3" json:"drop_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateConfig) Reset() {
	*x = TemplateConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateConfig) ProtoMessage() {}

func (x *TemplateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateConfig.ProtoReflect.Descriptor instead.
func (*TemplateConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{15}
}

func (x *TemplateConfig) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *TemplateConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateConfig) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TemplateConfig) GetStackSize() int32 {
	if x != nil {
		return x.StackSize
	}
	return 0
}

func (x *TemplateConfig) GetRespawnTicks() int32 {
	if x != nil {
		return x.RespawnTicks
	}
	return 0
}

func (x *TemplateConfig) GetTool() *ToolConfig {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *TemplateConfig) GetUseEffect() *UseEffectConfig {
	if x != nil {
		return x.UseEffect
	}
	return nil
}

func (x *TemplateConfig) GetDropTable() []*DropConfig {
	if x != nil {
		return x.DropTable
	}
	return nil
}

type ItemRefConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRefConfig) Reset() {
	*x = ItemRefConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRefConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRefConfig) ProtoMessage() {}

func (x *ItemRefConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRefConfig.ProtoReflect.Descriptor instead.
func (*ItemRefConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{16}
}

func (x *ItemRefConfig) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *ItemRefConfig) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecipeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workstation   WorkstationType        `protobuf:"varint,2,opt,name=workstation,proto3,enum=starve.game.v1.WorkstationType" json:"workstation,omitempty"` // 0 = 徒手可做
	Ticks         int32                  `protobuf:"varint,3,opt,name=ticks,proto3" json:"ticks,omitempty"`
	Output        *ItemRefConfig         `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Ingredients   []*ItemRefConfig       `protobuf:"bytes,5,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeConfig) Reset() {
	*x = RecipeConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeConfig) ProtoMessage() {}

func (x *RecipeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeConfig.ProtoReflect.Descriptor instead.
func (*RecipeConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{17}
}

func (x *RecipeConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeConfig) GetWorkstation() WorkstationType {
	if x != nil {
		return x.Workstation
	}
	return WorkstationType_WORKSTATION_TYPE_UNSPECIFIED
}

func (x *RecipeConfig) GetTicks() int32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

func (x *RecipeConfig) GetOutput() *ItemRefConfig {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RecipeConfig) GetIngredients() []*ItemRefConfig {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type StationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkstationType        `protobuf:"varint,1,opt,name=type,proto3,enum=starve.game.v1.WorkstationType" json:"type,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationConfig) Reset() {
	*x = StationConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationConfig) ProtoMessage() {}

func (x *StationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationConfig.ProtoReflect.Descriptor instead.
func (*StationConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{18}
}

func (x *StationConfig) GetType() WorkstationType {
	if x != nil {
		return x.Type
	}
	return WorkstationType_WORKSTATION_TYPE_UNSPECIFIED
}

func (x *StationConfig) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *StationConfig) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// GameConfig 世界配置的端上契约（模板/配方/工作站），登录后推送给客户端。
type GameConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateConfig      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Recipes       []*RecipeConfig        `protobuf:"bytes,2,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Stations      []*StationConfig       `protobuf:"bytes,3,rep,name=stations,proto3" json:"stations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{19}
}

func (x *GameConfig) GetTemplates() []*TemplateConfig {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *GameConfig) GetRecipes() []*RecipeConfig {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *GameConfig) GetStations() []*StationConfig {
	if x != nil {
		return x.Stations
	}
	return nil
}

// ItemStack 物品堆叠：kind + 数量 + 堆叠上限（上限 0 = 用模板默认）。
// 枚举键不能用 map，用 repeated 表达。
type ItemStack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	MaxStack      int32                  `protobuf:"varint,3,opt,name=max_stack,json=maxStack,proto3" json:"max_stack,omitempty"`
	Durability    int32                  `protobuf:"varint,4,opt,name=durability,proto3" json:"durability,omitempty"` // 工具剩余耐久（非工具为 0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStack) Reset() {
	*x = ItemStack{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStack) ProtoMessage() {}

func (x *ItemStack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStack.ProtoReflect.Descriptor instead.
func (*ItemStack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{20}
}

func (x *ItemStack) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *ItemStack) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemStack) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *ItemStack) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

// Inventory 玩家背包：物品堆叠列表（M5 二期最小形态；后续再加容量/槽位）。
type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStack           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{21}
}

func (x *Inventory) GetItems() []*ItemStack {
	if x != nil {
		return x.Items
	}
	return nil
}

// Loot 掉落物（死亡/砍伐实体就地转化）：捡走即消失。
type Loot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStack           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loot) Reset() {
	*x = Loot{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loot) ProtoMessage() {}

func (x *Loot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loot.ProtoReflect.Descriptor instead.
func (*Loot) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{22}
}

func (x *Loot) GetItems() []*ItemStack {
	if x != nil {
		return x.Items
	}
	return nil
}

// DayCycle 是世界级状态（Resource 的传输形态），不是实体组件。
type DayCycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         int32                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Light         float32                `protobuf:"fixed32,2,opt,name=light,proto3" json:"light,omitempty"` // 0..1 光照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayCycle) Reset() {
	*x = DayCycle{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayCycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayCycle) ProtoMessage() {}

func (x *DayCycle) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayCycle.ProtoReflect.Descriptor instead.
func (*DayCycle) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{23}
}

func (x *DayCycle) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *DayCycle) GetLight() float32 {
	if x != nil {
		return x.Light
	}
	return 0
}

type ComponentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // 组件名（如 "Health"），客户端按名解析
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`           // 组件值（codec 编码，protobuf）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentState) Reset() {
	*x = ComponentState{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentState) ProtoMessage() {}

func (x *ComponentState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentState.ProtoReflect.Descriptor instead.
func (*ComponentState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{24}
}

func (x *ComponentState) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ComponentState) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components    []*ComponentState      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{25}
}

func (x *EntityState) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetComponents() []*ComponentState {
	if x != nil {
		return x.Components
	}
	return nil
}

// RemovedComponent 本 tick 被移除的组件（实体保留，如资源耗尽）。
type RemovedComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components    []string               `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"` // 组件名，如 "Gatherable"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovedComponent) Reset() {
	*x = RemovedComponent{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovedComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovedComponent) ProtoMessage() {}

func (x *RemovedComponent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovedComponent.ProtoReflect.Descriptor instead.
func (*RemovedComponent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{26}
}

func (x *RemovedComponent) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *RemovedComponent) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

// 全量快照：登录/重连时发给单个客户端（重建本地实体表）。
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	DayCycle      *DayCycle              `protobuf:"bytes,2,opt,name=day_cycle,json=dayCycle,proto3" json:"day_cycle,omitempty"` // 世界级状态（昼夜）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{27}
}

func (x *Snapshot) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Snapshot) GetDayCycle() *DayCycle {
	if x != nil {
		return x.DayCycle
	}
	return nil
}

// 增量快照：每 tick 从 dirty 生成，广播（更新/删除）。
type SnapshotDelta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Entities          []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	RemovedEntities   []uint64               `protobuf:"varint,2,rep,packed,name=removed_entities,json=removedEntities,proto3" json:"removed_entities,omitempty"` // 本 tick 销毁的实体
	DayCycle          *DayCycle              `protobuf:"bytes,3,opt,name=day_cycle,json=dayCycle,proto3" json:"day_cycle,omitempty"`                              // 世界级状态（昼夜）
	RemovedComponents []*RemovedComponent    `protobuf:"bytes,4,rep,name=removed_components,json=removedComponents,proto3" json:"removed_components,omitempty"`   // 本 tick 被移除的组件
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotDelta) Reset() {
	*x = SnapshotDelta{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDelta) ProtoMessage() {}

func (x *SnapshotDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDelta.ProtoReflect.Descriptor instead.
func (*SnapshotDelta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{28}
}

func (x *SnapshotDelta) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SnapshotDelta) GetRemovedEntities() []uint64 {
	if x != nil {
		return x.RemovedEntities
	}
	return nil
}

func (x *SnapshotDelta) GetDayCycle() *DayCycle {
	if x != nil {
		return x.DayCycle
	}
	return nil
}

func (x *SnapshotDelta) GetRemovedComponents() []*RemovedComponent {
	if x != nil {
		return x.RemovedComponents
	}
	return nil
}

// WorldMeta 存档的世界元数据（实体 ID 分配状态 + 世界时钟）。
type WorldMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`                                       // 世界时钟（tick 数）
	NextEntityId  uint64                 `protobuf:"varint,2,opt,name=next_entity_id,json=nextEntityId,proto3" json:"next_entity_id,omitempty"` // 实体 ID 分配游标
	FreeIds       []uint64               `protobuf:"varint,3,rep,packed,name=free_ids,json=freeIds,proto3" json:"free_ids,omitempty"`           // 空闲 ID（销毁回收）
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                                  // 存档版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldMeta) Reset() {
	*x = WorldMeta{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldMeta) ProtoMessage() {}

func (x *WorldMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldMeta.ProtoReflect.Descriptor instead.
func (*WorldMeta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{29}
}

func (x *WorldMeta) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldMeta) GetNextEntityId() uint64 {
	if x != nil {
		return x.NextEntityId
	}
	return 0
}

func (x *WorldMeta) GetFreeIds() []uint64 {
	if x != nil {
		return x.FreeIds
	}
	return nil
}

func (x *WorldMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// SaveData 存档文件 = 全量快照 + 世界元数据。
type SaveData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Meta          *WorldMeta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Journal       []byte                 `protobuf:"bytes,3,opt,name=journal,proto3" json:"journal,omitempty"` // 指令日志（JSON 序列化，见 internal/game/world/command.go）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveData) Reset() {
	*x = SaveData{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveData) ProtoMessage() {}

func (x *SaveData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveData.ProtoReflect.Descriptor instead.
func (*SaveData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{30}
}

func (x *SaveData) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SaveData) GetMeta() *WorldMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SaveData) GetJournal() []byte {
	if x != nil {
		return x.Journal
	}
	return nil
}

var File_pkg_proto_game_game_proto protoreflect.FileDescriptor

const file_pkg_proto_game_game_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/game/game.proto\x12\x0estarve.game.v1\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\",\n" +
	"\x06Health\x12\x10\n" +
	"\x03cur\x18\x01 \x01(\x05R\x03cur\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"2\n" +
	"\x06Hunger\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x05R\x04rate\"6\n" +
	"\bGrowable\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\x05R\x05stage\x12\x14\n" +
	"\x05ticks\x18\x02 \x01(\x05R\x05ticks\"=\n" +
	"\x04Dead\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"since_tick\x18\x02 \x01(\x03R\tsinceTick\"\x1a\n" +
	"\x06Player\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"(\n" +
	"\aOffline\x12\x1d\n" +
	"\n" +
	"since_tick\x18\x01 \x01(\x03R\tsinceTick\"\xa4\x01\n" +
	"\bWorkable\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x122\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1a.starve.game.v1.WorkActionR\x06action\x12\x1b\n" +
	"\twork_left\x18\x03 \x01(\x05R\bworkLeft\x12\x19\n" +
	"\bmax_work\x18\x04 \x01(\x05R\amaxWork\"8\n" +
	"\bEquipped\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\"\x1f\n" +
	"\aRespawn\x12\x14\n" +
	"\x05ticks\x18\x01 \x01(\x03R\x05ticks\"B\n" +
	"\vWorkstation\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.starve.game.v1.WorkstationTypeR\x04type\"\x83\x01\n" +
	"\bCrafting\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x1d\n" +
	"\n" +
	"ticks_left\x18\x02 \x01(\x03R\tticksLeft\x12;\n" +
	"\vingredients\x18\x03 \x03(\v2\x19.starve.game.v1.ItemStackR\vingredients\"\x80\x01\n" +
	"\n" +
	"ToolConfig\x122\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1a.starve.game.v1.WorkActionR\x06action\x12\x1e\n" +
	"\n" +
	"efficiency\x18\x02 \x01(\x05R\n" +
	"efficiency\x12\x1e\n" +
	"\n" +
	"durability\x18\x03 \x01(\x05R\n" +
	"durability\"A\n" +
	"\x0fUseEffectConfig\x12\x16\n" +
	"\x06hunger\x18\x01 \x01(\x05R\x06hunger\x12\x16\n" +
	"\x06health\x18\x02 \x01(\x05R\x06health\"P\n" +
	"\n" +
	"DropConfig\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xd7\x02\n" +
	"\x0eTemplateConfig\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"stack_size\x18\x04 \x01(\x05R\tstackSize\x12#\n" +
	"\rrespawn_ticks\x18\x05 \x01(\x05R\frespawnTicks\x12.\n" +
	"\x04tool\x18\x06 \x01(\v2\x1a.starve.game.v1.ToolConfigR\x04tool\x12>\n" +
	"\n" +
	"use_effect\x18\a \x01(\v2\x1f.starve.game.v1.UseEffectConfigR\tuseEffect\x129\n" +
	"\n" +
	"drop_table\x18\b \x03(\v2\x1a.starve.game.v1.DropConfigR\tdropTable\"S\n" +
	"\rItemRefConfig\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xef\x01\n" +
	"\fRecipeConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\vworkstation\x18\x02 \x01(\x0e2\x1f.starve.game.v1.WorkstationTypeR\vworkstation\x12\x14\n" +
	"\x05ticks\x18\x03 \x01(\x05R\x05ticks\x125\n" +
	"\x06output\x18\x04 \x01(\v2\x1d.starve.game.v1.ItemRefConfigR\x06output\x12?\n" +
	"\vingredients\x18\x05 \x03(\v2\x1d.starve.game.v1.ItemRefConfigR\vingredients\"`\n" +
	"\rStationConfig\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.starve.game.v1.WorkstationTypeR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\xbd\x01\n" +
	"\n" +
	"GameConfig\x12<\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1e.starve.game.v1.TemplateConfigR\ttemplates\x126\n" +
	"\arecipes\x18\x02 \x03(\v2\x1c.starve.game.v1.RecipeConfigR\arecipes\x129\n" +
	"\bstations\x18\x03 \x03(\v2\x1d.starve.game.v1.StationConfigR\bstations\"\x8c\x01\n" +
	"\tItemStack\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1b\n" +
	"\tmax_stack\x18\x03 \x01(\x05R\bmaxStack\x12\x1e\n" +
	"\n" +
	"durability\x18\x04 \x01(\x05R\n" +
	"durability\"<\n" +
	"\tInventory\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.starve.game.v1.ItemStackR\x05items\"7\n" +
	"\x04Loot\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.starve.game.v1.ItemStackR\x05items\"6\n" +
	"\bDayCycle\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x05R\x05phase\x12\x14\n" +
	"\x05light\x18\x02 \x01(\x02R\x05light\"B\n" +
	"\x0eComponentState\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"j\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12>\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x1e.starve.game.v1.ComponentStateR\n" +
	"components\"O\n" +
	"\x10RemovedComponent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1e\n" +
	"\n" +
	"components\x18\x02 \x03(\tR\n" +
	"components\"z\n" +
	"\bSnapshot\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.starve.game.v1.EntityStateR\bentities\x125\n" +
	"\tday_cycle\x18\x02 \x01(\v2\x18.starve.game.v1.DayCycleR\bdayCycle\"\xfb\x01\n" +
	"\rSnapshotDelta\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.starve.game.v1.EntityStateR\bentities\x12)\n" +
	"\x10removed_entities\x18\x02 \x03(\x04R\x0fremovedEntities\x125\n" +
	"\tday_cycle\x18\x03 \x01(\v2\x18.starve.game.v1.DayCycleR\bdayCycle\x12O\n" +
	"\x12removed_components\x18\x04 \x03(\v2 .starve.game.v1.RemovedComponentR\x11removedComponents\"z\n" +
	"\tWorldMeta\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12$\n" +
	"\x0enext_entity_id\x18\x02 \x01(\x04R\fnextEntityId\x12\x19\n" +
	"\bfree_ids\x18\x03 \x03(\x04R\afreeIds\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\x89\x01\n" +
	"\bSaveData\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x18.starve.game.v1.SnapshotR\bsnapshot\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.starve.game.v1.WorldMetaR\x04meta\x12\x18\n" +
	"\ajournal\x18\x03 \x01(\fR\ajournal*\x8d\x01\n" +
	"\bItemKind\x12\x19\n" +
	"\x15ITEM_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fITEM_KIND_BERRY\x10\x01\x12\x12\n" +
	"\x0eITEM_KIND_WOOD\x10\x02\x12\x13\n" +
	"\x0fITEM_KIND_FLINT\x10\x03\x12\x11\n" +
	"\rITEM_KIND_AXE\x10d\x12\x15\n" +
	"\x11ITEM_KIND_PICKAXE\x10e*k\n" +
	"\n" +
	"WorkAction\x12\x1b\n" +
	"\x17WORK_ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10WORK_ACTION_CHOP\x10\x01\x12\x14\n" +
	"\x10WORK_ACTION_MINE\x10\x02\x12\x14\n" +
	"\x10WORK_ACTION_PICK\x10\x03*r\n" +
	"\x0fWorkstationType\x12 \n" +
	"\x1cWORKSTATION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKSTATION_TYPE_CAMPFIRE\x10\x01\x12\x1e\n" +
	"\x1aWORKSTATION_TYPE_WORKBENCH\x10\x02B\x17Z\x15starve/pkg/proto/gameb\x06proto3"

var (
	file_pkg_proto_game_game_proto_rawDescOnce sync.Once
	file_pkg_proto_game_game_proto_rawDescData []byte
)

func file_pkg_proto_game_game_proto_rawDescGZIP() []byte {
	file_pkg_proto_game_game_proto_rawDescOnce.Do(func() {
		file_pkg_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_game_game_proto_rawDesc), len(file_pkg_proto_game_game_proto_rawDesc)))
	})
	return file_pkg_proto_game_game_proto_rawDescData
}

var file_pkg_proto_game_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_pkg_proto_game_game_proto_goTypes = []any{
	(ItemKind)(0),            // 0: starve.game.v1.ItemKind
	(WorkAction)(0),          // 1: starve.game.v1.WorkAction
	(WorkstationType)(0),     // 2: starve.game.v1.WorkstationType
	(*Position)(nil),         // 3: starve.game.v1.Position
	(*Health)(nil),           // 4: starve.game.v1.Health
	(*Hunger)(nil),           // 5: starve.game.v1.Hunger
	(*Growable)(nil),         // 6: starve.game.v1.Growable
	(*Dead)(nil),             // 7: starve.game.v1.Dead
	(*Player)(nil),           // 8: starve.game.v1.Player
	(*Offline)(nil),          // 9: starve.game.v1.Offline
	(*Workable)(nil),         // 10: starve.game.v1.Workable
	(*Equipped)(nil),         // 11: starve.game.v1.Equipped
	(*Respawn)(nil),          // 12: starve.game.v1.Respawn
	(*Workstation)(nil),      // 13: starve.game.v1.Workstation
	(*Crafting)(nil),         // 14: starve.game.v1.Crafting
	(*ToolConfig)(nil),       // 15: starve.game.v1.ToolConfig
	(*UseEffectConfig)(nil),  // 16: starve.game.v1.UseEffectConfig
	(*DropConfig)(nil),       // 17: starve.game.v1.DropConfig
	(*TemplateConfig)(nil),   // 18: starve.game.v1.TemplateConfig
	(*ItemRefConfig)(nil),    // 19: starve.game.v1.ItemRefConfig
	(*RecipeConfig)(nil),     // 20: starve.game.v1.RecipeConfig
	(*StationConfig)(nil),    // 21: starve.game.v1.StationConfig
	(*GameConfig)(nil),       // 22: starve.game.v1.GameConfig
	(*ItemStack)(nil),        // 23: starve.game.v1.ItemStack
	(*Inventory)(nil),        // 24: starve.game.v1.Inventory
	(*Loot)(nil),             // 25: starve.game.v1.Loot
	(*DayCycle)(nil),         // 26: starve.game.v1.DayCycle
	(*ComponentState)(nil),   // 27: starve.game.v1.ComponentState
	(*EntityState)(nil),      // 28: starve.game.v1.EntityState
	(*RemovedComponent)(nil), // 29: starve.game.v1.RemovedComponent
	(*Snapshot)(nil),         // 30: starve.game.v1.Snapshot
	(*SnapshotDelta)(nil),    // 31: starve.game.v1.SnapshotDelta
	(*WorldMeta)(nil),        // 32: starve.game.v1.WorldMeta
	(*SaveData)(nil),         // 33: starve.game.v1.SaveData
}
var file_pkg_proto_game_game_proto_depIdxs = []int32{
	0,  // 0: starve.game.v1.Workable.kind:type_name -> starve.game.v1.ItemKind
	1,  // 1: starve.game.v1.Workable.action:type_name -> starve.game.v1.WorkAction
	0,  // 2: starve.game.v1.Equipped.kind:type_name -> starve.game.v1.ItemKind
	2,  // 3: starve.game.v1.Workstation.type:type_name -> starve.game.v1.WorkstationType
	23, // 4: starve.game.v1.Crafting.ingredients:type_name -> starve.game.v1.ItemStack
	1,  // 5: starve.game.v1.ToolConfig.action:type_name -> starve.game.v1.WorkAction
	0,  // 6: starve.game.v1.DropConfig.kind:type_name -> starve.game.v1.ItemKind
	0,  // 7: starve.game.v1.TemplateConfig.kind:type_name -> starve.game.v1.ItemKind
	15, // 8: starve.game.v1.TemplateConfig.tool:type_name -> starve.game.v1.ToolConfig
	16, // 9: starve.game.v1.TemplateConfig.use_effect:type_name -> starve.game.v1.UseEffectConfig
	17, // 10: starve.game.v1.TemplateConfig.drop_table:type_name -> starve.game.v1.DropConfig
	0,  // 11: starve.game.v1.ItemRefConfig.kind:type_name -> starve.game.v1.ItemKind
	2,  // 12: starve.game.v1.RecipeConfig.workstation:type_name -> starve.game.v1.WorkstationType
	19, // 13: starve.game.v1.RecipeConfig.output:type_name -> starve.game.v1.ItemRefConfig
	19, // 14: starve.game.v1.RecipeConfig.ingredients:type_name -> starve.game.v1.ItemRefConfig
	2,  // 15: starve.game.v1.StationConfig.type:type_name -> starve.game.v1.WorkstationType
	18, // 16: starve.game.v1.GameConfig.templates:type_name -> starve.game.v1.TemplateConfig
	20, // 17: starve.game.v1.GameConfig.recipes:type_name -> starve.game.v1.RecipeConfig
	21, // 18: starve.game.v1.GameConfig.stations:type_name -> starve.game.v1.StationConfig
	0,  // 19: starve.game.v1.ItemStack.kind:type_name -> starve.game.v1.ItemKind
	23, // 20: starve.game.v1.Inventory.items:type_name -> starve.game.v1.ItemStack
	23, // 21: starve.game.v1.Loot.items:type_name -> starve.game.v1.ItemStack
	27, // 22: starve.game.v1.EntityState.components:type_name -> starve.game.v1.ComponentState
	28, // 23: starve.game.v1.Snapshot.entities:type_name -> starve.game.v1.EntityState
	26, // 24: starve.game.v1.Snapshot.day_cycle:type_name -> starve.game.v1.DayCycle
	28, // 25: starve.game.v1.SnapshotDelta.entities:type_name -> starve.game.v1.EntityState
	26, // 26: starve.game.v1.SnapshotDelta.day_cycle:type_name -> starve.game.v1.DayCycle
	29, // 27: starve.game.v1.SnapshotDelta.removed_components:type_name -> starve.game.v1.RemovedComponent
	30, // 28: starve.game.v1.SaveData.snapshot:type_name -> starve.game.v1.Snapshot
	32, // 29: starve.game.v1.SaveData.meta:type_name -> starve.game.v1.WorldMeta
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_pkg_proto_game_game_proto_init() }
func file_pkg_proto_game_game_proto_init() {
	if File_pkg_proto_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_game_game_proto_rawDesc), len(file_pkg_proto_game_game_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_game_game_proto_goTypes,
		DependencyIndexes: file_pkg_proto_game_game_proto_depIdxs,
		EnumInfos:         file_pkg_proto_game_game_proto_enumTypes,
		MessageInfos:      file_pkg_proto_game_game_proto_msgTypes,
	}.Build()
	File_pkg_proto_game_game_proto = out.File
	file_pkg_proto_game_game_proto_goTypes = nil
	file_pkg_proto_game_game_proto_depIdxs = nil
}
