// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/proto/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cur           int32                  `protobuf:"varint,1,opt,name=cur,proto3" json:"cur,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *Health) GetCur() int32 {
	if x != nil {
		return x.Cur
	}
	return 0
}

func (x *Health) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Hunger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Rate          int32                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"` // 每 tick 消耗速率（0 表示用世界默认）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hunger) Reset() {
	*x = Hunger{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunger) ProtoMessage() {}

func (x *Hunger) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunger.ProtoReflect.Descriptor instead.
func (*Hunger) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *Hunger) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Hunger) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Growable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         int32                  `protobuf:"varint,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Ticks         int32                  `protobuf:"varint,2,opt,name=ticks,proto3" json:"ticks,omitempty"` // 距上次生长经过的 tick 数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Growable) Reset() {
	*x = Growable{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Growable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Growable) ProtoMessage() {}

func (x *Growable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Growable.ProtoReflect.Descriptor instead.
func (*Growable) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *Growable) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Growable) GetTicks() int32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

// Dead 死亡标记：实体死后保留在世界上（尸体/幽灵状态），由后续系统处理。
type Dead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dead) Reset() {
	*x = Dead{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dead) ProtoMessage() {}

func (x *Dead) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dead.ProtoReflect.Descriptor instead.
func (*Dead) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *Dead) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Player 玩家标记：把 UID（账号）挂到实体上，快照携带，加载时重建所有权表。
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *Player) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// DayCycle 是世界级状态（Resource 的传输形态），不是实体组件。
type DayCycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         int32                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Light         float32                `protobuf:"fixed32,2,opt,name=light,proto3" json:"light,omitempty"` // 0..1 光照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayCycle) Reset() {
	*x = DayCycle{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayCycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayCycle) ProtoMessage() {}

func (x *DayCycle) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayCycle.ProtoReflect.Descriptor instead.
func (*DayCycle) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{6}
}

func (x *DayCycle) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *DayCycle) GetLight() float32 {
	if x != nil {
		return x.Light
	}
	return 0
}

type ComponentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // 组件名（如 "Health"），客户端按名解析
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`           // 组件值（codec 编码，protobuf）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentState) Reset() {
	*x = ComponentState{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentState) ProtoMessage() {}

func (x *ComponentState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentState.ProtoReflect.Descriptor instead.
func (*ComponentState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{7}
}

func (x *ComponentState) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ComponentState) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components    []*ComponentState      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{8}
}

func (x *EntityState) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetComponents() []*ComponentState {
	if x != nil {
		return x.Components
	}
	return nil
}

// 全量快照：登录/重连时发给单个客户端（重建本地实体表）。
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	DayCycle      *DayCycle              `protobuf:"bytes,2,opt,name=day_cycle,json=dayCycle,proto3" json:"day_cycle,omitempty"` // 世界级状态（昼夜）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{9}
}

func (x *Snapshot) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Snapshot) GetDayCycle() *DayCycle {
	if x != nil {
		return x.DayCycle
	}
	return nil
}

// 增量快照：每 tick 从 dirty 生成，广播（更新/删除）。
type SnapshotDelta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Entities        []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	RemovedEntities []uint64               `protobuf:"varint,2,rep,packed,name=removed_entities,json=removedEntities,proto3" json:"removed_entities,omitempty"` // 本 tick 销毁的实体
	DayCycle        *DayCycle              `protobuf:"bytes,3,opt,name=day_cycle,json=dayCycle,proto3" json:"day_cycle,omitempty"`                              // 世界级状态（昼夜）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotDelta) Reset() {
	*x = SnapshotDelta{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDelta) ProtoMessage() {}

func (x *SnapshotDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDelta.ProtoReflect.Descriptor instead.
func (*SnapshotDelta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotDelta) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SnapshotDelta) GetRemovedEntities() []uint64 {
	if x != nil {
		return x.RemovedEntities
	}
	return nil
}

func (x *SnapshotDelta) GetDayCycle() *DayCycle {
	if x != nil {
		return x.DayCycle
	}
	return nil
}

// WorldMeta 存档的世界元数据（实体 ID 分配状态 + 世界时钟）。
type WorldMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`                                       // 世界时钟（tick 数）
	NextEntityId  uint64                 `protobuf:"varint,2,opt,name=next_entity_id,json=nextEntityId,proto3" json:"next_entity_id,omitempty"` // 实体 ID 分配游标
	FreeIds       []uint64               `protobuf:"varint,3,rep,packed,name=free_ids,json=freeIds,proto3" json:"free_ids,omitempty"`           // 空闲 ID（销毁回收）
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                                  // 存档版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldMeta) Reset() {
	*x = WorldMeta{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldMeta) ProtoMessage() {}

func (x *WorldMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldMeta.ProtoReflect.Descriptor instead.
func (*WorldMeta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{11}
}

func (x *WorldMeta) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldMeta) GetNextEntityId() uint64 {
	if x != nil {
		return x.NextEntityId
	}
	return 0
}

func (x *WorldMeta) GetFreeIds() []uint64 {
	if x != nil {
		return x.FreeIds
	}
	return nil
}

func (x *WorldMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// SaveData 存档文件 = 全量快照 + 世界元数据。
type SaveData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Meta          *WorldMeta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveData) Reset() {
	*x = SaveData{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveData) ProtoMessage() {}

func (x *SaveData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveData.ProtoReflect.Descriptor instead.
func (*SaveData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{12}
}

func (x *SaveData) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SaveData) GetMeta() *WorldMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_pkg_proto_game_game_proto protoreflect.FileDescriptor

const file_pkg_proto_game_game_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/game/game.proto\x12\x0estarve.game.v1\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\",\n" +
	"\x06Health\x12\x10\n" +
	"\x03cur\x18\x01 \x01(\x05R\x03cur\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"2\n" +
	"\x06Hunger\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x05R\x04rate\"6\n" +
	"\bGrowable\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\x05R\x05stage\x12\x14\n" +
	"\x05ticks\x18\x02 \x01(\x05R\x05ticks\"\x1e\n" +
	"\x04Dead\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x1a\n" +
	"\x06Player\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"6\n" +
	"\bDayCycle\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x05R\x05phase\x12\x14\n" +
	"\x05light\x18\x02 \x01(\x02R\x05light\"B\n" +
	"\x0eComponentState\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"j\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12>\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x1e.starve.game.v1.ComponentStateR\n" +
	"components\"z\n" +
	"\bSnapshot\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.starve.game.v1.EntityStateR\bentities\x125\n" +
	"\tday_cycle\x18\x02 \x01(\v2\x18.starve.game.v1.DayCycleR\bdayCycle\"\xaa\x01\n" +
	"\rSnapshotDelta\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.starve.game.v1.EntityStateR\bentities\x12)\n" +
	"\x10removed_entities\x18\x02 \x03(\x04R\x0fremovedEntities\x125\n" +
	"\tday_cycle\x18\x03 \x01(\v2\x18.starve.game.v1.DayCycleR\bdayCycle\"z\n" +
	"\tWorldMeta\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12$\n" +
	"\x0enext_entity_id\x18\x02 \x01(\x04R\fnextEntityId\x12\x19\n" +
	"\bfree_ids\x18\x03 \x03(\x04R\afreeIds\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"o\n" +
	"\bSaveData\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x18.starve.game.v1.SnapshotR\bsnapshot\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.starve.game.v1.WorldMetaR\x04metaB\x17Z\x15starve/pkg/proto/gameb\x06proto3"

var (
	file_pkg_proto_game_game_proto_rawDescOnce sync.Once
	file_pkg_proto_game_game_proto_rawDescData []byte
)

func file_pkg_proto_game_game_proto_rawDescGZIP() []byte {
	file_pkg_proto_game_game_proto_rawDescOnce.Do(func() {
		file_pkg_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_game_game_proto_rawDesc), len(file_pkg_proto_game_game_proto_rawDesc)))
	})
	return file_pkg_proto_game_game_proto_rawDescData
}

var file_pkg_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_proto_game_game_proto_goTypes = []any{
	(*Position)(nil),       // 0: starve.game.v1.Position
	(*Health)(nil),         // 1: starve.game.v1.Health
	(*Hunger)(nil),         // 2: starve.game.v1.Hunger
	(*Growable)(nil),       // 3: starve.game.v1.Growable
	(*Dead)(nil),           // 4: starve.game.v1.Dead
	(*Player)(nil),         // 5: starve.game.v1.Player
	(*DayCycle)(nil),       // 6: starve.game.v1.DayCycle
	(*ComponentState)(nil), // 7: starve.game.v1.ComponentState
	(*EntityState)(nil),    // 8: starve.game.v1.EntityState
	(*Snapshot)(nil),       // 9: starve.game.v1.Snapshot
	(*SnapshotDelta)(nil),  // 10: starve.game.v1.SnapshotDelta
	(*WorldMeta)(nil),      // 11: starve.game.v1.WorldMeta
	(*SaveData)(nil),       // 12: starve.game.v1.SaveData
}
var file_pkg_proto_game_game_proto_depIdxs = []int32{
	7,  // 0: starve.game.v1.EntityState.components:type_name -> starve.game.v1.ComponentState
	8,  // 1: starve.game.v1.Snapshot.entities:type_name -> starve.game.v1.EntityState
	6,  // 2: starve.game.v1.Snapshot.day_cycle:type_name -> starve.game.v1.DayCycle
	8,  // 3: starve.game.v1.SnapshotDelta.entities:type_name -> starve.game.v1.EntityState
	6,  // 4: starve.game.v1.SnapshotDelta.day_cycle:type_name -> starve.game.v1.DayCycle
	9,  // 5: starve.game.v1.SaveData.snapshot:type_name -> starve.game.v1.Snapshot
	11, // 6: starve.game.v1.SaveData.meta:type_name -> starve.game.v1.WorldMeta
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_game_game_proto_init() }
func file_pkg_proto_game_game_proto_init() {
	if File_pkg_proto_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_game_game_proto_rawDesc), len(file_pkg_proto_game_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_game_game_proto_goTypes,
		DependencyIndexes: file_pkg_proto_game_game_proto_depIdxs,
		MessageInfos:      file_pkg_proto_game_game_proto_msgTypes,
	}.Build()
	File_pkg_proto_game_game_proto = out.File
	file_pkg_proto_game_game_proto_goTypes = nil
	file_pkg_proto_game_game_proto_depIdxs = nil
}
