// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/proto/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemKind 物品/实体类型（稳定 ID）：资源、工具等共用一个枚举。
// 新类型 = 新枚举值 + 模板表条目（样式/颜色/掉落等静态属性在模板表，不在枚举）。
type ItemKind int32

const (
	ItemKind_ITEM_KIND_UNSPECIFIED ItemKind = 0
	// 资源段 1-99
	ItemKind_ITEM_KIND_BERRY ItemKind = 1
	ItemKind_ITEM_KIND_WOOD  ItemKind = 2
	ItemKind_ITEM_KIND_FLINT ItemKind = 3
	// 工具段 100-199
	ItemKind_ITEM_KIND_AXE     ItemKind = 100 // 工具（砍伐）
	ItemKind_ITEM_KIND_PICKAXE ItemKind = 101 // 工具（挖掘）
)

// Enum value maps for ItemKind.
var (
	ItemKind_name = map[int32]string{
		0:   "ITEM_KIND_UNSPECIFIED",
		1:   "ITEM_KIND_BERRY",
		2:   "ITEM_KIND_WOOD",
		3:   "ITEM_KIND_FLINT",
		100: "ITEM_KIND_AXE",
		101: "ITEM_KIND_PICKAXE",
	}
	ItemKind_value = map[string]int32{
		"ITEM_KIND_UNSPECIFIED": 0,
		"ITEM_KIND_BERRY":       1,
		"ITEM_KIND_WOOD":        2,
		"ITEM_KIND_FLINT":       3,
		"ITEM_KIND_AXE":         100,
		"ITEM_KIND_PICKAXE":     101,
	}
)

func (x ItemKind) Enum() *ItemKind {
	p := new(ItemKind)
	*p = x
	return p
}

func (x ItemKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[0].Descriptor()
}

func (ItemKind) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[0]
}

func (x ItemKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemKind.Descriptor instead.
func (ItemKind) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{0}
}

// WorkAction 可交互动作（目标声明能被什么动作处理，工具声明做什么动作）。
type WorkAction int32

const (
	WorkAction_WORK_ACTION_UNSPECIFIED WorkAction = 0
	WorkAction_WORK_ACTION_CHOP        WorkAction = 1 // 砍伐（树）
	WorkAction_WORK_ACTION_MINE        WorkAction = 2 // 挖掘（矿）
	WorkAction_WORK_ACTION_PICK        WorkAction = 3 // 采集（浆果丛）
)

// Enum value maps for WorkAction.
var (
	WorkAction_name = map[int32]string{
		0: "WORK_ACTION_UNSPECIFIED",
		1: "WORK_ACTION_CHOP",
		2: "WORK_ACTION_MINE",
		3: "WORK_ACTION_PICK",
	}
	WorkAction_value = map[string]int32{
		"WORK_ACTION_UNSPECIFIED": 0,
		"WORK_ACTION_CHOP":        1,
		"WORK_ACTION_MINE":        2,
		"WORK_ACTION_PICK":        3,
	}
)

func (x WorkAction) Enum() *WorkAction {
	p := new(WorkAction)
	*p = x
	return p
}

func (x WorkAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkAction) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[1].Descriptor()
}

func (WorkAction) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[1]
}

func (x WorkAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkAction.Descriptor instead.
func (WorkAction) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{1}
}

// WorkstationType 工作站类型（稳定 ID）。
type WorkstationType int32

const (
	WorkstationType_WORKSTATION_TYPE_UNSPECIFIED WorkstationType = 0
	WorkstationType_WORKSTATION_TYPE_CAMPFIRE    WorkstationType = 1 // 火堆
	WorkstationType_WORKSTATION_TYPE_WORKBENCH   WorkstationType = 2 // 工作台
)

// Enum value maps for WorkstationType.
var (
	WorkstationType_name = map[int32]string{
		0: "WORKSTATION_TYPE_UNSPECIFIED",
		1: "WORKSTATION_TYPE_CAMPFIRE",
		2: "WORKSTATION_TYPE_WORKBENCH",
	}
	WorkstationType_value = map[string]int32{
		"WORKSTATION_TYPE_UNSPECIFIED": 0,
		"WORKSTATION_TYPE_CAMPFIRE":    1,
		"WORKSTATION_TYPE_WORKBENCH":   2,
	}
)

func (x WorkstationType) Enum() *WorkstationType {
	p := new(WorkstationType)
	*p = x
	return p
}

func (x WorkstationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkstationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[2].Descriptor()
}

func (WorkstationType) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[2]
}

func (x WorkstationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkstationType.Descriptor instead.
func (WorkstationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{2}
}

// EffectOrder 效果类型 + 确定性应用顺序（枚举值即结算顺序，越小越先）。
// 效果的强度走 EffectInstance.param（配置/发射器携带），效果实现按 param 结算，
// 同一效果只写一个枚举值（如加速/减速都是 SPEED，param 正负决定方向）。
// 新效果：加枚举值 + 在组件包实现 Effect 接口并在 init 注册，零改动系统。
type EffectOrder int32

const (
	EffectOrder_EFFECT_ORDER_UNSPECIFIED EffectOrder = 0
	EffectOrder_EFFECT_ORDER_SPEED       EffectOrder = 1 // 速度修正：param = 百分比（正=加速，负=减速）
	EffectOrder_EFFECT_ORDER_POISON      EffectOrder = 2 // 中毒：param = 每 tick 扣血量（0 = 默认 1）
	EffectOrder_EFFECT_ORDER_COLD        EffectOrder = 3 // 寒冷：param = 每 tick 冻伤量（天气派生）
	EffectOrder_EFFECT_ORDER_HEAT        EffectOrder = 4 // 炎热：param = 每 tick 中暑量（天气派生）
)

// Enum value maps for EffectOrder.
var (
	EffectOrder_name = map[int32]string{
		0: "EFFECT_ORDER_UNSPECIFIED",
		1: "EFFECT_ORDER_SPEED",
		2: "EFFECT_ORDER_POISON",
		3: "EFFECT_ORDER_COLD",
		4: "EFFECT_ORDER_HEAT",
	}
	EffectOrder_value = map[string]int32{
		"EFFECT_ORDER_UNSPECIFIED": 0,
		"EFFECT_ORDER_SPEED":       1,
		"EFFECT_ORDER_POISON":      2,
		"EFFECT_ORDER_COLD":        3,
		"EFFECT_ORDER_HEAT":        4,
	}
)

func (x EffectOrder) Enum() *EffectOrder {
	p := new(EffectOrder)
	*p = x
	return p
}

func (x EffectOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[3].Descriptor()
}

func (EffectOrder) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[3]
}

func (x EffectOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectOrder.Descriptor instead.
func (EffectOrder) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{3}
}

// Season 季节（由世界时钟推导，随存档自动恢复）。
type Season int32

const (
	Season_SEASON_UNSPECIFIED Season = 0
	Season_SEASON_SPRING      Season = 1
	Season_SEASON_SUMMER      Season = 2
	Season_SEASON_AUTUMN      Season = 3
	Season_SEASON_WINTER      Season = 4
)

// Enum value maps for Season.
var (
	Season_name = map[int32]string{
		0: "SEASON_UNSPECIFIED",
		1: "SEASON_SPRING",
		2: "SEASON_SUMMER",
		3: "SEASON_AUTUMN",
		4: "SEASON_WINTER",
	}
	Season_value = map[string]int32{
		"SEASON_UNSPECIFIED": 0,
		"SEASON_SPRING":      1,
		"SEASON_SUMMER":      2,
		"SEASON_AUTUMN":      3,
		"SEASON_WINTER":      4,
	}
)

func (x Season) Enum() *Season {
	p := new(Season)
	*p = x
	return p
}

func (x Season) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Season) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[4].Descriptor()
}

func (Season) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[4]
}

func (x Season) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Season.Descriptor instead.
func (Season) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{4}
}

// TerrainType 地形类型（角粒度，客户端按枚举映射颜色/贴图，零代码扩展）。
type TerrainType int32

const (
	TerrainType_TERRAIN_TYPE_UNSPECIFIED TerrainType = 0
	TerrainType_TERRAIN_TYPE_WATER       TerrainType = 1
	TerrainType_TERRAIN_TYPE_SAND        TerrainType = 2
	TerrainType_TERRAIN_TYPE_GRASS       TerrainType = 3
	TerrainType_TERRAIN_TYPE_ROCK        TerrainType = 4
	TerrainType_TERRAIN_TYPE_SNOW        TerrainType = 5
)

// Enum value maps for TerrainType.
var (
	TerrainType_name = map[int32]string{
		0: "TERRAIN_TYPE_UNSPECIFIED",
		1: "TERRAIN_TYPE_WATER",
		2: "TERRAIN_TYPE_SAND",
		3: "TERRAIN_TYPE_GRASS",
		4: "TERRAIN_TYPE_ROCK",
		5: "TERRAIN_TYPE_SNOW",
	}
	TerrainType_value = map[string]int32{
		"TERRAIN_TYPE_UNSPECIFIED": 0,
		"TERRAIN_TYPE_WATER":       1,
		"TERRAIN_TYPE_SAND":        2,
		"TERRAIN_TYPE_GRASS":       3,
		"TERRAIN_TYPE_ROCK":        4,
		"TERRAIN_TYPE_SNOW":        5,
	}
)

func (x TerrainType) Enum() *TerrainType {
	p := new(TerrainType)
	*p = x
	return p
}

func (x TerrainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerrainType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_game_game_proto_enumTypes[5].Descriptor()
}

func (TerrainType) Type() protoreflect.EnumType {
	return &file_pkg_proto_game_game_proto_enumTypes[5]
}

func (x TerrainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerrainType.Descriptor instead.
func (TerrainType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{5}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Moveable 可移动实体（玩家）的 tick 制移动状态：
// move 命令是方向步进，进 Queue 缓存；MoveSystem 每 tick 按步进间隔消费队首。
type Moveable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      int32                  `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"` // 基础步进间隔（tick/格，如 2 = 每 2 tick 走一格）
	Elapsed       int32                  `protobuf:"varint,2,opt,name=elapsed,proto3" json:"elapsed,omitempty"`   // 距上次移动经过的 tick 数
	Queue         []*MoveDir             `protobuf:"bytes,3,rep,name=queue,proto3" json:"queue,omitempty"`        // 待执行方向（顺序应用；收到 0,0 停止命令时清空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moveable) Reset() {
	*x = Moveable{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moveable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moveable) ProtoMessage() {}

func (x *Moveable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moveable.ProtoReflect.Descriptor instead.
func (*Moveable) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *Moveable) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Moveable) GetElapsed() int32 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

func (x *Moveable) GetQueue() []*MoveDir {
	if x != nil {
		return x.Queue
	}
	return nil
}

type MoveDir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dx            int32                  `protobuf:"varint,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,2,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveDir) Reset() {
	*x = MoveDir{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveDir) ProtoMessage() {}

func (x *MoveDir) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveDir.ProtoReflect.Descriptor instead.
func (*MoveDir) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *MoveDir) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *MoveDir) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cur           int32                  `protobuf:"varint,1,opt,name=cur,proto3" json:"cur,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *Health) GetCur() int32 {
	if x != nil {
		return x.Cur
	}
	return 0
}

func (x *Health) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Hunger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Rate          int32                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"` // 每 tick 消耗速率（0 表示用世界默认）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hunger) Reset() {
	*x = Hunger{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunger) ProtoMessage() {}

func (x *Hunger) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunger.ProtoReflect.Descriptor instead.
func (*Hunger) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *Hunger) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Hunger) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Growable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         int32                  `protobuf:"varint,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Ticks         int32                  `protobuf:"varint,2,opt,name=ticks,proto3" json:"ticks,omitempty"` // 距上次生长经过的 tick 数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Growable) Reset() {
	*x = Growable{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Growable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Growable) ProtoMessage() {}

func (x *Growable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Growable.ProtoReflect.Descriptor instead.
func (*Growable) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *Growable) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *Growable) GetTicks() int32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

// Dead 死亡标记：实体死后保留在世界上（尸体/幽灵状态），由后续系统处理。
type Dead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	SinceTick     int64                  `protobuf:"varint,2,opt,name=since_tick,json=sinceTick,proto3" json:"since_tick,omitempty"` // 死亡起始世界 tick（尸体清理用；旧档为 0 时世界自动补盖）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dead) Reset() {
	*x = Dead{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dead) ProtoMessage() {}

func (x *Dead) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dead.ProtoReflect.Descriptor instead.
func (*Dead) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{6}
}

func (x *Dead) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Dead) GetSinceTick() int64 {
	if x != nil {
		return x.SinceTick
	}
	return 0
}

// Player 玩家标记：把 UID（账号）挂到实体上，快照携带，加载时重建所有权表。
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{7}
}

func (x *Player) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Offline 离线标记：断线后实体保留在世界上（断线保留 N 分钟），重连复用。
type Offline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SinceTick     int64                  `protobuf:"varint,1,opt,name=since_tick,json=sinceTick,proto3" json:"since_tick,omitempty"` // 离线起始世界 tick（用于超时清理）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offline) Reset() {
	*x = Offline{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offline) ProtoMessage() {}

func (x *Offline) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offline.ProtoReflect.Descriptor instead.
func (*Offline) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{8}
}

func (x *Offline) GetSinceTick() int64 {
	if x != nil {
		return x.SinceTick
	}
	return 0
}

// Workable 可交互环境物（树/矿/浆果丛）：动作 + 剩余工作量。
// 用 WorkLeft 表达耐久（不用 Combat Health）：砍伐/挖掘/采集走工作量，
// 生物才用 Health——两条伤害通道互不干扰。
type Workable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`       // 实体类型（掉落/模板查找用）
	Action        WorkAction             `protobuf:"varint,2,opt,name=action,proto3,enum=starve.game.v1.WorkAction" json:"action,omitempty"` // 能被什么动作处理
	WorkLeft      int32                  `protobuf:"varint,3,opt,name=work_left,json=workLeft,proto3" json:"work_left,omitempty"`
	MaxWork       int32                  `protobuf:"varint,4,opt,name=max_work,json=maxWork,proto3" json:"max_work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workable) Reset() {
	*x = Workable{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workable) ProtoMessage() {}

func (x *Workable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workable.ProtoReflect.Descriptor instead.
func (*Workable) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{9}
}

func (x *Workable) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *Workable) GetAction() WorkAction {
	if x != nil {
		return x.Action
	}
	return WorkAction_WORK_ACTION_UNSPECIFIED
}

func (x *Workable) GetWorkLeft() int32 {
	if x != nil {
		return x.WorkLeft
	}
	return 0
}

func (x *Workable) GetMaxWork() int32 {
	if x != nil {
		return x.MaxWork
	}
	return 0
}

// Equipped 玩家当前手持的工具（kind=0 表示徒手）。
type Equipped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Equipped) Reset() {
	*x = Equipped{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Equipped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equipped) ProtoMessage() {}

func (x *Equipped) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equipped.ProtoReflect.Descriptor instead.
func (*Equipped) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{10}
}

func (x *Equipped) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

// Respawn 重生标记：有该组件的环境物在耗尽后会自动恢复（如浆果丛重新长出）。
type Respawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticks         int64                  `protobuf:"varint,1,opt,name=ticks,proto3" json:"ticks,omitempty"` // 剩余倒计时（tick）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respawn) Reset() {
	*x = Respawn{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respawn) ProtoMessage() {}

func (x *Respawn) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respawn.ProtoReflect.Descriptor instead.
func (*Respawn) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{11}
}

func (x *Respawn) GetTicks() int64 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

// Workstation 工作站标记：某些配方要求玩家附近有指定类型的工作站。
type Workstation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkstationType        `protobuf:"varint,1,opt,name=type,proto3,enum=starve.game.v1.WorkstationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workstation) Reset() {
	*x = Workstation{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workstation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workstation) ProtoMessage() {}

func (x *Workstation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workstation.ProtoReflect.Descriptor instead.
func (*Workstation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{12}
}

func (x *Workstation) GetType() WorkstationType {
	if x != nil {
		return x.Type
	}
	return WorkstationType_WORKSTATION_TYPE_UNSPECIFIED
}

// Crafting 制作中的状态（挂在玩家身上）：配方 + 剩余 tick。
type Crafting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	TicksLeft     int64                  `protobuf:"varint,2,opt,name=ticks_left,json=ticksLeft,proto3" json:"ticks_left,omitempty"`
	Ingredients   []*ItemStack           `protobuf:"bytes,3,rep,name=ingredients,proto3" json:"ingredients,omitempty"` // 打断退款用（craft 开始时从配方拷贝）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Crafting) Reset() {
	*x = Crafting{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Crafting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crafting) ProtoMessage() {}

func (x *Crafting) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crafting.ProtoReflect.Descriptor instead.
func (*Crafting) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{13}
}

func (x *Crafting) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *Crafting) GetTicksLeft() int64 {
	if x != nil {
		return x.TicksLeft
	}
	return 0
}

func (x *Crafting) GetIngredients() []*ItemStack {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

// EffectInstance 一个效果实例：类型 + 参数（如毒伤量、速度修正百分比）。
type EffectInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         EffectOrder            `protobuf:"varint,1,opt,name=order,proto3,enum=starve.game.v1.EffectOrder" json:"order,omitempty"`
	Param         int32                  `protobuf:"varint,2,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectInstance) Reset() {
	*x = EffectInstance{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectInstance) ProtoMessage() {}

func (x *EffectInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectInstance.ProtoReflect.Descriptor instead.
func (*EffectInstance) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{14}
}

func (x *EffectInstance) GetOrder() EffectOrder {
	if x != nil {
		return x.Order
	}
	return EffectOrder_EFFECT_ORDER_UNSPECIFIED
}

func (x *EffectInstance) GetParam() int32 {
	if x != nil {
		return x.Param
	}
	return 0
}

// EffectActive 单个效果的覆盖状态：多来源计数 + 聚合参数（多来源求和）。
type EffectActive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         EffectOrder            `protobuf:"varint,1,opt,name=order,proto3,enum=starve.game.v1.EffectOrder" json:"order,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Param         int32                  `protobuf:"varint,3,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectActive) Reset() {
	*x = EffectActive{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectActive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectActive) ProtoMessage() {}

func (x *EffectActive) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectActive.ProtoReflect.Descriptor instead.
func (*EffectActive) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{15}
}

func (x *EffectActive) GetOrder() EffectOrder {
	if x != nil {
		return x.Order
	}
	return EffectOrder_EFFECT_ORDER_UNSPECIFIED
}

func (x *EffectActive) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EffectActive) GetParam() int32 {
	if x != nil {
		return x.Param
	}
	return 0
}

// Effects 实体当前生效效果（挂在玩家身上；进快照，客户端渲染 buff/debuff 图标）。
type Effects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        []*EffectActive        `protobuf:"bytes,1,rep,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effects) Reset() {
	*x = Effects{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effects) ProtoMessage() {}

func (x *Effects) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effects.ProtoReflect.Descriptor instead.
func (*Effects) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{16}
}

func (x *Effects) GetActive() []*EffectActive {
	if x != nil {
		return x.Active
	}
	return nil
}

// EffectEmitter 效果发射器（植物/火堆等实体挂载）：
// effects 为效果集合，radius 为作用半径（0 = 仅影响自身所在格）。
type EffectEmitter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effects       []*EffectInstance      `protobuf:"bytes,1,rep,name=effects,proto3" json:"effects,omitempty"`
	Radius        int32                  `protobuf:"varint,2,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectEmitter) Reset() {
	*x = EffectEmitter{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectEmitter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectEmitter) ProtoMessage() {}

func (x *EffectEmitter) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectEmitter.ProtoReflect.Descriptor instead.
func (*EffectEmitter) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{17}
}

func (x *EffectEmitter) GetEffects() []*EffectInstance {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *EffectEmitter) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// WeatherState 天气世界状态（随快照下发/存档；phase 驱动确定性采样）。
type WeatherState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         int64                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`                              // 时间相位（世界 tick）
	Season        Season                 `protobuf:"varint,2,opt,name=season,proto3,enum=starve.game.v1.Season" json:"season,omitempty"` // 由 phase 推导（冗余给客户端显示）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherState) Reset() {
	*x = WeatherState{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherState) ProtoMessage() {}

func (x *WeatherState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherState.ProtoReflect.Descriptor instead.
func (*WeatherState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{18}
}

func (x *WeatherState) GetPhase() int64 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *WeatherState) GetSeason() Season {
	if x != nil {
		return x.Season
	}
	return Season_SEASON_UNSPECIFIED
}

// Fan 风扇：局部风力修正 + 下风向雾密度降低（实体组件）。
type Fan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"`     // 风力（叠加到风速）
	DirX          int32                  `protobuf:"varint,2,opt,name=dir_x,json=dirX,proto3" json:"dir_x,omitempty"` // 风向（-1/0/1，采样时归一化）
	DirY          int32                  `protobuf:"varint,3,opt,name=dir_y,json=dirY,proto3" json:"dir_y,omitempty"`
	Radius        int32                  `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fan) Reset() {
	*x = Fan{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fan) ProtoMessage() {}

func (x *Fan) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fan.ProtoReflect.Descriptor instead.
func (*Fan) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{19}
}

func (x *Fan) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Fan) GetDirX() int32 {
	if x != nil {
		return x.DirX
	}
	return 0
}

func (x *Fan) GetDirY() int32 {
	if x != nil {
		return x.DirY
	}
	return 0
}

func (x *Fan) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// HeatSource 热源（火堆等）：局部升温 + 降雾（实体组件）。
type HeatSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"` // 升温量
	Radius        int32                  `protobuf:"varint,2,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatSource) Reset() {
	*x = HeatSource{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatSource) ProtoMessage() {}

func (x *HeatSource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatSource.ProtoReflect.Descriptor instead.
func (*HeatSource) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{20}
}

func (x *HeatSource) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *HeatSource) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// WeatherCell 天气网格单元（粗粒度：一个单元覆盖 cell_size × cell_size 世界格）。
type WeatherCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fog           float32                `protobuf:"fixed32,1,opt,name=fog,proto3" json:"fog,omitempty"`                 // 0..1（客户端按值叠加雾层透明度）
	Rain          float32                `protobuf:"fixed32,2,opt,name=rain,proto3" json:"rain,omitempty"`               // 0..1（客户端按值决定雨粒子密度/速度）
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"` // 摄氏度（客户端可做季节色调/结冰效果）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherCell) Reset() {
	*x = WeatherCell{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherCell) ProtoMessage() {}

func (x *WeatherCell) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherCell.ProtoReflect.Descriptor instead.
func (*WeatherCell) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{21}
}

func (x *WeatherCell) GetFog() float32 {
	if x != nil {
		return x.Fog
	}
	return 0
}

func (x *WeatherCell) GetRain() float32 {
	if x != nil {
		return x.Rain
	}
	return 0
}

func (x *WeatherCell) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// WeatherFrame 天气帧（服务端 → 客户端，周期推送）：客户端据此渲染雾/雨/风向。
// cells 行优先，共 cells_per_row × (总格数 / cell_size) 个单元，覆盖全图。
type WeatherFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Season        Season                 `protobuf:"varint,1,opt,name=season,proto3,enum=starve.game.v1.Season" json:"season,omitempty"`
	CellSize      int32                  `protobuf:"varint,2,opt,name=cell_size,json=cellSize,proto3" json:"cell_size,omitempty"`            // 每个采样单元覆盖的世界格数（如 10 = 10×10 一格）
	CellsPerRow   int32                  `protobuf:"varint,3,opt,name=cells_per_row,json=cellsPerRow,proto3" json:"cells_per_row,omitempty"` // 每行单元数
	Cells         []*WeatherCell         `protobuf:"bytes,4,rep,name=cells,proto3" json:"cells,omitempty"`
	WindDirX      float32                `protobuf:"fixed32,5,opt,name=wind_dir_x,json=windDirX,proto3" json:"wind_dir_x,omitempty"` // 全局风向（单位向量）
	WindDirY      float32                `protobuf:"fixed32,6,opt,name=wind_dir_y,json=windDirY,proto3" json:"wind_dir_y,omitempty"`
	WindSpeed     float32                `protobuf:"fixed32,7,opt,name=wind_speed,json=windSpeed,proto3" json:"wind_speed,omitempty"` // 全局风速（雨粒子漂移/旗帜摆动用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherFrame) Reset() {
	*x = WeatherFrame{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherFrame) ProtoMessage() {}

func (x *WeatherFrame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherFrame.ProtoReflect.Descriptor instead.
func (*WeatherFrame) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{22}
}

func (x *WeatherFrame) GetSeason() Season {
	if x != nil {
		return x.Season
	}
	return Season_SEASON_UNSPECIFIED
}

func (x *WeatherFrame) GetCellSize() int32 {
	if x != nil {
		return x.CellSize
	}
	return 0
}

func (x *WeatherFrame) GetCellsPerRow() int32 {
	if x != nil {
		return x.CellsPerRow
	}
	return 0
}

func (x *WeatherFrame) GetCells() []*WeatherCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *WeatherFrame) GetWindDirX() float32 {
	if x != nil {
		return x.WindDirX
	}
	return 0
}

func (x *WeatherFrame) GetWindDirY() float32 {
	if x != nil {
		return x.WindDirY
	}
	return 0
}

func (x *WeatherFrame) GetWindSpeed() float32 {
	if x != nil {
		return x.WindSpeed
	}
	return 0
}

type ToolConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        WorkAction             `protobuf:"varint,1,opt,name=action,proto3,enum=starve.game.v1.WorkAction" json:"action,omitempty"`
	Efficiency    int32                  `protobuf:"varint,2,opt,name=efficiency,proto3" json:"efficiency,omitempty"`
	Durability    int32                  `protobuf:"varint,3,opt,name=durability,proto3" json:"durability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolConfig) Reset() {
	*x = ToolConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolConfig) ProtoMessage() {}

func (x *ToolConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolConfig.ProtoReflect.Descriptor instead.
func (*ToolConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{23}
}

func (x *ToolConfig) GetAction() WorkAction {
	if x != nil {
		return x.Action
	}
	return WorkAction_WORK_ACTION_UNSPECIFIED
}

func (x *ToolConfig) GetEfficiency() int32 {
	if x != nil {
		return x.Efficiency
	}
	return 0
}

func (x *ToolConfig) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

type UseEffectConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hunger        int32                  `protobuf:"varint,1,opt,name=hunger,proto3" json:"hunger,omitempty"`
	Health        int32                  `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseEffectConfig) Reset() {
	*x = UseEffectConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseEffectConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseEffectConfig) ProtoMessage() {}

func (x *UseEffectConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseEffectConfig.ProtoReflect.Descriptor instead.
func (*UseEffectConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{24}
}

func (x *UseEffectConfig) GetHunger() int32 {
	if x != nil {
		return x.Hunger
	}
	return 0
}

func (x *UseEffectConfig) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type DropConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropConfig) Reset() {
	*x = DropConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropConfig) ProtoMessage() {}

func (x *DropConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropConfig.ProtoReflect.Descriptor instead.
func (*DropConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{25}
}

func (x *DropConfig) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *DropConfig) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TemplateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	StackSize     int32                  `protobuf:"varint,4,opt,name=stack_size,json=stackSize,proto3" json:"stack_size,omitempty"`
	RespawnTicks  int32                  `protobuf:"varint,5,opt,name=respawn_ticks,json=respawnTicks,proto3" json:"respawn_ticks,omitempty"`
	Tool          *ToolConfig            `protobuf:"bytes,6,opt,name=tool,proto3" json:"tool,omitempty"`
	UseEffect     *UseEffectConfig       `protobuf:"bytes,7,opt,name=use_effect,json=useEffect,proto3" json:"use_effect,omitempty"`
	DropTable     []*DropConfig          `protobuf:"bytes,8,rep,name=drop_table,json=dropTable,proto3" json:"drop_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateConfig) Reset() {
	*x = TemplateConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateConfig) ProtoMessage() {}

func (x *TemplateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateConfig.ProtoReflect.Descriptor instead.
func (*TemplateConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{26}
}

func (x *TemplateConfig) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *TemplateConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateConfig) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TemplateConfig) GetStackSize() int32 {
	if x != nil {
		return x.StackSize
	}
	return 0
}

func (x *TemplateConfig) GetRespawnTicks() int32 {
	if x != nil {
		return x.RespawnTicks
	}
	return 0
}

func (x *TemplateConfig) GetTool() *ToolConfig {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *TemplateConfig) GetUseEffect() *UseEffectConfig {
	if x != nil {
		return x.UseEffect
	}
	return nil
}

func (x *TemplateConfig) GetDropTable() []*DropConfig {
	if x != nil {
		return x.DropTable
	}
	return nil
}

type ItemRefConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRefConfig) Reset() {
	*x = ItemRefConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRefConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRefConfig) ProtoMessage() {}

func (x *ItemRefConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRefConfig.ProtoReflect.Descriptor instead.
func (*ItemRefConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{27}
}

func (x *ItemRefConfig) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *ItemRefConfig) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RecipeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workstation   WorkstationType        `protobuf:"varint,2,opt,name=workstation,proto3,enum=starve.game.v1.WorkstationType" json:"workstation,omitempty"` // 0 = 徒手可做
	Ticks         int32                  `protobuf:"varint,3,opt,name=ticks,proto3" json:"ticks,omitempty"`
	Output        *ItemRefConfig         `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Ingredients   []*ItemRefConfig       `protobuf:"bytes,5,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeConfig) Reset() {
	*x = RecipeConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeConfig) ProtoMessage() {}

func (x *RecipeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeConfig.ProtoReflect.Descriptor instead.
func (*RecipeConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{28}
}

func (x *RecipeConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeConfig) GetWorkstation() WorkstationType {
	if x != nil {
		return x.Workstation
	}
	return WorkstationType_WORKSTATION_TYPE_UNSPECIFIED
}

func (x *RecipeConfig) GetTicks() int32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

func (x *RecipeConfig) GetOutput() *ItemRefConfig {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RecipeConfig) GetIngredients() []*ItemRefConfig {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type StationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkstationType        `protobuf:"varint,1,opt,name=type,proto3,enum=starve.game.v1.WorkstationType" json:"type,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationConfig) Reset() {
	*x = StationConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationConfig) ProtoMessage() {}

func (x *StationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationConfig.ProtoReflect.Descriptor instead.
func (*StationConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{29}
}

func (x *StationConfig) GetType() WorkstationType {
	if x != nil {
		return x.Type
	}
	return WorkstationType_WORKSTATION_TYPE_UNSPECIFIED
}

func (x *StationConfig) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *StationConfig) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// MapConfig 地形高度场（静态，登录随 world.config 下发、随存档保存/恢复）。
// corner_heights/corner_types 都是 (width+1)×(height+1) 个字节，行优先。
type MapConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`                                     // 格子列数
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`                                   // 格子行数
	CornerHeights []byte                 `protobuf:"bytes,3,opt,name=corner_heights,json=cornerHeights,proto3" json:"corner_heights,omitempty"` // 每角高度 0~255
	CornerTypes   []byte                 `protobuf:"bytes,4,opt,name=corner_types,json=cornerTypes,proto3" json:"corner_types,omitempty"`       // 每角 TerrainType 枚举值
	SpawnX        int32                  `protobuf:"varint,5,opt,name=spawn_x,json=spawnX,proto3" json:"spawn_x,omitempty"`
	SpawnY        int32                  `protobuf:"varint,6,opt,name=spawn_y,json=spawnY,proto3" json:"spawn_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapConfig) Reset() {
	*x = MapConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapConfig) ProtoMessage() {}

func (x *MapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapConfig.ProtoReflect.Descriptor instead.
func (*MapConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{30}
}

func (x *MapConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapConfig) GetCornerHeights() []byte {
	if x != nil {
		return x.CornerHeights
	}
	return nil
}

func (x *MapConfig) GetCornerTypes() []byte {
	if x != nil {
		return x.CornerTypes
	}
	return nil
}

func (x *MapConfig) GetSpawnX() int32 {
	if x != nil {
		return x.SpawnX
	}
	return 0
}

func (x *MapConfig) GetSpawnY() int32 {
	if x != nil {
		return x.SpawnY
	}
	return 0
}

// GameConfig 世界配置的端上契约（模板/配方/工作站），登录后推送给客户端。
type GameConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Templates      []*TemplateConfig      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Recipes        []*RecipeConfig        `protobuf:"bytes,2,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Stations       []*StationConfig       `protobuf:"bytes,3,rep,name=stations,proto3" json:"stations,omitempty"`
	InventorySlots int32                  `protobuf:"varint,4,opt,name=inventory_slots,json=inventorySlots,proto3" json:"inventory_slots,omitempty"` // 背包格数（客户端渲染格子面板用）
	Map            *MapConfig             `protobuf:"bytes,5,opt,name=map,proto3" json:"map,omitempty"`                                              // 地形高度场（静态，随存档恢复）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{31}
}

func (x *GameConfig) GetTemplates() []*TemplateConfig {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *GameConfig) GetRecipes() []*RecipeConfig {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *GameConfig) GetStations() []*StationConfig {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *GameConfig) GetInventorySlots() int32 {
	if x != nil {
		return x.InventorySlots
	}
	return 0
}

func (x *GameConfig) GetMap() *MapConfig {
	if x != nil {
		return x.Map
	}
	return nil
}

// ItemStack 物品堆叠：kind + 数量 + 堆叠上限（上限 0 = 用模板默认）。
// 枚举键不能用 map，用 repeated 表达。
type ItemStack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ItemKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=starve.game.v1.ItemKind" json:"kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	MaxStack      int32                  `protobuf:"varint,3,opt,name=max_stack,json=maxStack,proto3" json:"max_stack,omitempty"`
	Durability    int32                  `protobuf:"varint,4,opt,name=durability,proto3" json:"durability,omitempty"` // 工具剩余耐久（非工具为 0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStack) Reset() {
	*x = ItemStack{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStack) ProtoMessage() {}

func (x *ItemStack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStack.ProtoReflect.Descriptor instead.
func (*ItemStack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{32}
}

func (x *ItemStack) GetKind() ItemKind {
	if x != nil {
		return x.Kind
	}
	return ItemKind_ITEM_KIND_UNSPECIFIED
}

func (x *ItemStack) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ItemStack) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *ItemStack) GetDurability() int32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

// Inventory 玩家背包：物品堆叠列表（M5 二期最小形态；后续再加容量/槽位）。
// Inventory 玩家背包：槽位数组（固定容量，空槽 = 空 ItemStack）。
type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStack           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 顺序 = 槽位顺序（含空槽）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{33}
}

func (x *Inventory) GetItems() []*ItemStack {
	if x != nil {
		return x.Items
	}
	return nil
}

// Loot 掉落物（死亡/砍伐实体就地转化）：捡走即消失。
type Loot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStack           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loot) Reset() {
	*x = Loot{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loot) ProtoMessage() {}

func (x *Loot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loot.ProtoReflect.Descriptor instead.
func (*Loot) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{34}
}

func (x *Loot) GetItems() []*ItemStack {
	if x != nil {
		return x.Items
	}
	return nil
}

// DayCycle 是世界级状态（Resource 的传输形态），不是实体组件。
type DayCycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         int32                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Light         float32                `protobuf:"fixed32,2,opt,name=light,proto3" json:"light,omitempty"` // 0..1 光照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayCycle) Reset() {
	*x = DayCycle{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayCycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayCycle) ProtoMessage() {}

func (x *DayCycle) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayCycle.ProtoReflect.Descriptor instead.
func (*DayCycle) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{35}
}

func (x *DayCycle) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *DayCycle) GetLight() float32 {
	if x != nil {
		return x.Light
	}
	return 0
}

type ComponentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // 组件名（如 "Health"），客户端按名解析
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`           // 组件值（codec 编码，protobuf）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentState) Reset() {
	*x = ComponentState{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentState) ProtoMessage() {}

func (x *ComponentState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentState.ProtoReflect.Descriptor instead.
func (*ComponentState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{36}
}

func (x *ComponentState) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ComponentState) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components    []*ComponentState      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{37}
}

func (x *EntityState) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetComponents() []*ComponentState {
	if x != nil {
		return x.Components
	}
	return nil
}

// RemovedComponent 本 tick 被移除的组件（实体保留，如资源耗尽）。
type RemovedComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Components    []string               `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"` // 组件名，如 "Gatherable"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovedComponent) Reset() {
	*x = RemovedComponent{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovedComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovedComponent) ProtoMessage() {}

func (x *RemovedComponent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovedComponent.ProtoReflect.Descriptor instead.
func (*RemovedComponent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{38}
}

func (x *RemovedComponent) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *RemovedComponent) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

// 全量快照：登录/重连时发给单个客户端（重建本地实体表）。
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	DayCycle      *DayCycle              `protobuf:"bytes,2,opt,name=day_cycle,json=dayCycle,proto3" json:"day_cycle,omitempty"` // 世界级状态（昼夜）
	Weather       *WeatherState          `protobuf:"bytes,3,opt,name=weather,proto3" json:"weather,omitempty"`                   // 世界级状态（天气相位/季节）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{39}
}

func (x *Snapshot) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Snapshot) GetDayCycle() *DayCycle {
	if x != nil {
		return x.DayCycle
	}
	return nil
}

func (x *Snapshot) GetWeather() *WeatherState {
	if x != nil {
		return x.Weather
	}
	return nil
}

// 增量快照：每 tick 从 dirty 生成，广播（更新/删除）。
type SnapshotDelta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Entities          []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	RemovedEntities   []uint64               `protobuf:"varint,2,rep,packed,name=removed_entities,json=removedEntities,proto3" json:"removed_entities,omitempty"` // 本 tick 销毁的实体
	DayCycle          *DayCycle              `protobuf:"bytes,3,opt,name=day_cycle,json=dayCycle,proto3" json:"day_cycle,omitempty"`                              // 世界级状态（昼夜）
	RemovedComponents []*RemovedComponent    `protobuf:"bytes,4,rep,name=removed_components,json=removedComponents,proto3" json:"removed_components,omitempty"`   // 本 tick 被移除的组件
	Weather           *WeatherState          `protobuf:"bytes,5,opt,name=weather,proto3" json:"weather,omitempty"`                                                // 世界级状态（天气相位/季节）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotDelta) Reset() {
	*x = SnapshotDelta{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDelta) ProtoMessage() {}

func (x *SnapshotDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDelta.ProtoReflect.Descriptor instead.
func (*SnapshotDelta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{40}
}

func (x *SnapshotDelta) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SnapshotDelta) GetRemovedEntities() []uint64 {
	if x != nil {
		return x.RemovedEntities
	}
	return nil
}

func (x *SnapshotDelta) GetDayCycle() *DayCycle {
	if x != nil {
		return x.DayCycle
	}
	return nil
}

func (x *SnapshotDelta) GetRemovedComponents() []*RemovedComponent {
	if x != nil {
		return x.RemovedComponents
	}
	return nil
}

func (x *SnapshotDelta) GetWeather() *WeatherState {
	if x != nil {
		return x.Weather
	}
	return nil
}

// WorldMeta 存档的世界元数据（实体 ID 分配状态 + 世界时钟）。
type WorldMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`                                       // 世界时钟（tick 数）
	NextEntityId  uint64                 `protobuf:"varint,2,opt,name=next_entity_id,json=nextEntityId,proto3" json:"next_entity_id,omitempty"` // 实体 ID 分配游标
	FreeIds       []uint64               `protobuf:"varint,3,rep,packed,name=free_ids,json=freeIds,proto3" json:"free_ids,omitempty"`           // 空闲 ID（销毁回收）
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                                  // 存档版本
	MapSeed       uint64                 `protobuf:"varint,5,opt,name=map_seed,json=mapSeed,proto3" json:"map_seed,omitempty"`                  // 地图生成种子（重放/复现用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldMeta) Reset() {
	*x = WorldMeta{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldMeta) ProtoMessage() {}

func (x *WorldMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldMeta.ProtoReflect.Descriptor instead.
func (*WorldMeta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{41}
}

func (x *WorldMeta) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *WorldMeta) GetNextEntityId() uint64 {
	if x != nil {
		return x.NextEntityId
	}
	return 0
}

func (x *WorldMeta) GetFreeIds() []uint64 {
	if x != nil {
		return x.FreeIds
	}
	return nil
}

func (x *WorldMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorldMeta) GetMapSeed() uint64 {
	if x != nil {
		return x.MapSeed
	}
	return 0
}

// SaveData 存档文件 = 全量快照 + 世界元数据。
type SaveData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Meta          *WorldMeta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	Journal       []byte                 `protobuf:"bytes,3,opt,name=journal,proto3" json:"journal,omitempty"`                            // 指令日志（JSON 序列化，见 internal/game/world/command.go）
	Map           *MapConfig             `protobuf:"bytes,4,opt,name=map,proto3" json:"map,omitempty"`                                    // 地形高度场（静态，随存档恢复）
	TileEffects   []byte                 `protobuf:"bytes,5,opt,name=tile_effects,json=tileEffects,proto3" json:"tile_effects,omitempty"` // W×H 每格效果 id（服务端内部，随档保存，不下发客户端）
	TileParams    []byte                 `protobuf:"bytes,6,opt,name=tile_params,json=tileParams,proto3" json:"tile_params,omitempty"`    // W×H 每格效果参数（服务端内部，随档保存，不下发客户端）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveData) Reset() {
	*x = SaveData{}
	mi := &file_pkg_proto_game_game_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveData) ProtoMessage() {}

func (x *SaveData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_game_game_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveData.ProtoReflect.Descriptor instead.
func (*SaveData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_game_game_proto_rawDescGZIP(), []int{42}
}

func (x *SaveData) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SaveData) GetMeta() *WorldMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SaveData) GetJournal() []byte {
	if x != nil {
		return x.Journal
	}
	return nil
}

func (x *SaveData) GetMap() *MapConfig {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *SaveData) GetTileEffects() []byte {
	if x != nil {
		return x.TileEffects
	}
	return nil
}

func (x *SaveData) GetTileParams() []byte {
	if x != nil {
		return x.TileParams
	}
	return nil
}

var File_pkg_proto_game_game_proto protoreflect.FileDescriptor

const file_pkg_proto_game_game_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/game/game.proto\x12\x0estarve.game.v1\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"o\n" +
	"\bMoveable\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x05R\binterval\x12\x18\n" +
	"\aelapsed\x18\x02 \x01(\x05R\aelapsed\x12-\n" +
	"\x05queue\x18\x03 \x03(\v2\x17.starve.game.v1.MoveDirR\x05queue\")\n" +
	"\aMoveDir\x12\x0e\n" +
	"\x02dx\x18\x01 \x01(\x05R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x02 \x01(\x05R\x02dy\",\n" +
	"\x06Health\x12\x10\n" +
	"\x03cur\x18\x01 \x01(\x05R\x03cur\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"2\n" +
	"\x06Hunger\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x05R\x04rate\"6\n" +
	"\bGrowable\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\x05R\x05stage\x12\x14\n" +
	"\x05ticks\x18\x02 \x01(\x05R\x05ticks\"=\n" +
	"\x04Dead\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"since_tick\x18\x02 \x01(\x03R\tsinceTick\"\x1a\n" +
	"\x06Player\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"(\n" +
	"\aOffline\x12\x1d\n" +
	"\n" +
	"since_tick\x18\x01 \x01(\x03R\tsinceTick\"\xa4\x01\n" +
	"\bWorkable\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x122\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1a.starve.game.v1.WorkActionR\x06action\x12\x1b\n" +
	"\twork_left\x18\x03 \x01(\x05R\bworkLeft\x12\x19\n" +
	"\bmax_work\x18\x04 \x01(\x05R\amaxWork\"8\n" +
	"\bEquipped\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\"\x1f\n" +
	"\aRespawn\x12\x14\n" +
	"\x05ticks\x18\x01 \x01(\x03R\x05ticks\"B\n" +
	"\vWorkstation\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.starve.game.v1.WorkstationTypeR\x04type\"\x83\x01\n" +
	"\bCrafting\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\x12\x1d\n" +
	"\n" +
	"ticks_left\x18\x02 \x01(\x03R\tticksLeft\x12;\n" +
	"\vingredients\x18\x03 \x03(\v2\x19.starve.game.v1.ItemStackR\vingredients\"Y\n" +
	"\x0eEffectInstance\x121\n" +
	"\x05order\x18\x01 \x01(\x0e2\x1b.starve.game.v1.EffectOrderR\x05order\x12\x14\n" +
	"\x05param\x18\x02 \x01(\x05R\x05param\"m\n" +
	"\fEffectActive\x121\n" +
	"\x05order\x18\x01 \x01(\x0e2\x1b.starve.game.v1.EffectOrderR\x05order\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05param\x18\x03 \x01(\x05R\x05param\"?\n" +
	"\aEffects\x124\n" +
	"\x06active\x18\x01 \x03(\v2\x1c.starve.game.v1.EffectActiveR\x06active\"a\n" +
	"\rEffectEmitter\x128\n" +
	"\aeffects\x18\x01 \x03(\v2\x1e.starve.game.v1.EffectInstanceR\aeffects\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x05R\x06radius\"T\n" +
	"\fWeatherState\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x03R\x05phase\x12.\n" +
	"\x06season\x18\x02 \x01(\x0e2\x16.starve.game.v1.SeasonR\x06season\"c\n" +
	"\x03Fan\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\x12\x13\n" +
	"\x05dir_x\x18\x02 \x01(\x05R\x04dirX\x12\x13\n" +
	"\x05dir_y\x18\x03 \x01(\x05R\x04dirY\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x05R\x06radius\"@\n" +
	"\n" +
	"HeatSource\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x05R\x06radius\"U\n" +
	"\vWeatherCell\x12\x10\n" +
	"\x03fog\x18\x01 \x01(\x02R\x03fog\x12\x12\n" +
	"\x04rain\x18\x02 \x01(\x02R\x04rain\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\"\x8d\x02\n" +
	"\fWeatherFrame\x12.\n" +
	"\x06season\x18\x01 \x01(\x0e2\x16.starve.game.v1.SeasonR\x06season\x12\x1b\n" +
	"\tcell_size\x18\x02 \x01(\x05R\bcellSize\x12\"\n" +
	"\rcells_per_row\x18\x03 \x01(\x05R\vcellsPerRow\x121\n" +
	"\x05cells\x18\x04 \x03(\v2\x1b.starve.game.v1.WeatherCellR\x05cells\x12\x1c\n" +
	"\n" +
	"wind_dir_x\x18\x05 \x01(\x02R\bwindDirX\x12\x1c\n" +
	"\n" +
	"wind_dir_y\x18\x06 \x01(\x02R\bwindDirY\x12\x1d\n" +
	"\n" +
	"wind_speed\x18\a \x01(\x02R\twindSpeed\"\x80\x01\n" +
	"\n" +
	"ToolConfig\x122\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1a.starve.game.v1.WorkActionR\x06action\x12\x1e\n" +
	"\n" +
	"efficiency\x18\x02 \x01(\x05R\n" +
	"efficiency\x12\x1e\n" +
	"\n" +
	"durability\x18\x03 \x01(\x05R\n" +
	"durability\"A\n" +
	"\x0fUseEffectConfig\x12\x16\n" +
	"\x06hunger\x18\x01 \x01(\x05R\x06hunger\x12\x16\n" +
	"\x06health\x18\x02 \x01(\x05R\x06health\"P\n" +
	"\n" +
	"DropConfig\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xd7\x02\n" +
	"\x0eTemplateConfig\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"stack_size\x18\x04 \x01(\x05R\tstackSize\x12#\n" +
	"\rrespawn_ticks\x18\x05 \x01(\x05R\frespawnTicks\x12.\n" +
	"\x04tool\x18\x06 \x01(\v2\x1a.starve.game.v1.ToolConfigR\x04tool\x12>\n" +
	"\n" +
	"use_effect\x18\a \x01(\v2\x1f.starve.game.v1.UseEffectConfigR\tuseEffect\x129\n" +
	"\n" +
	"drop_table\x18\b \x03(\v2\x1a.starve.game.v1.DropConfigR\tdropTable\"S\n" +
	"\rItemRefConfig\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xef\x01\n" +
	"\fRecipeConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\vworkstation\x18\x02 \x01(\x0e2\x1f.starve.game.v1.WorkstationTypeR\vworkstation\x12\x14\n" +
	"\x05ticks\x18\x03 \x01(\x05R\x05ticks\x125\n" +
	"\x06output\x18\x04 \x01(\v2\x1d.starve.game.v1.ItemRefConfigR\x06output\x12?\n" +
	"\vingredients\x18\x05 \x03(\v2\x1d.starve.game.v1.ItemRefConfigR\vingredients\"`\n" +
	"\rStationConfig\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.starve.game.v1.WorkstationTypeR\x04type\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\xb5\x01\n" +
	"\tMapConfig\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12%\n" +
	"\x0ecorner_heights\x18\x03 \x01(\fR\rcornerHeights\x12!\n" +
	"\fcorner_types\x18\x04 \x01(\fR\vcornerTypes\x12\x17\n" +
	"\aspawn_x\x18\x05 \x01(\x05R\x06spawnX\x12\x17\n" +
	"\aspawn_y\x18\x06 \x01(\x05R\x06spawnY\"\x93\x02\n" +
	"\n" +
	"GameConfig\x12<\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1e.starve.game.v1.TemplateConfigR\ttemplates\x126\n" +
	"\arecipes\x18\x02 \x03(\v2\x1c.starve.game.v1.RecipeConfigR\arecipes\x129\n" +
	"\bstations\x18\x03 \x03(\v2\x1d.starve.game.v1.StationConfigR\bstations\x12'\n" +
	"\x0finventory_slots\x18\x04 \x01(\x05R\x0einventorySlots\x12+\n" +
	"\x03map\x18\x05 \x01(\v2\x19.starve.game.v1.MapConfigR\x03map\"\x8c\x01\n" +
	"\tItemStack\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.starve.game.v1.ItemKindR\x04kind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1b\n" +
	"\tmax_stack\x18\x03 \x01(\x05R\bmaxStack\x12\x1e\n" +
	"\n" +
	"durability\x18\x04 \x01(\x05R\n" +
	"durability\"<\n" +
	"\tInventory\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.starve.game.v1.ItemStackR\x05items\"7\n" +
	"\x04Loot\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.starve.game.v1.ItemStackR\x05items\"6\n" +
	"\bDayCycle\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x05R\x05phase\x12\x14\n" +
	"\x05light\x18\x02 \x01(\x02R\x05light\"B\n" +
	"\x0eComponentState\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"j\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12>\n" +
	"\n" +
	"components\x18\x02 \x03(\v2\x1e.starve.game.v1.ComponentStateR\n" +
	"components\"O\n" +
	"\x10RemovedComponent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1e\n" +
	"\n" +
	"components\x18\x02 \x03(\tR\n" +
	"components\"\xb2\x01\n" +
	"\bSnapshot\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.starve.game.v1.EntityStateR\bentities\x125\n" +
	"\tday_cycle\x18\x02 \x01(\v2\x18.starve.game.v1.DayCycleR\bdayCycle\x126\n" +
	"\aweather\x18\x03 \x01(\v2\x1c.starve.game.v1.WeatherStateR\aweather\"\xb3\x02\n" +
	"\rSnapshotDelta\x127\n" +
	"\bentities\x18\x01 \x03(\v2\x1b.starve.game.v1.EntityStateR\bentities\x12)\n" +
	"\x10removed_entities\x18\x02 \x03(\x04R\x0fremovedEntities\x125\n" +
	"\tday_cycle\x18\x03 \x01(\v2\x18.starve.game.v1.DayCycleR\bdayCycle\x12O\n" +
	"\x12removed_components\x18\x04 \x03(\v2 .starve.game.v1.RemovedComponentR\x11removedComponents\x126\n" +
	"\aweather\x18\x05 \x01(\v2\x1c.starve.game.v1.WeatherStateR\aweather\"\x95\x01\n" +
	"\tWorldMeta\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12$\n" +
	"\x0enext_entity_id\x18\x02 \x01(\x04R\fnextEntityId\x12\x19\n" +
	"\bfree_ids\x18\x03 \x03(\x04R\afreeIds\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x19\n" +
	"\bmap_seed\x18\x05 \x01(\x04R\amapSeed\"\xfa\x01\n" +
	"\bSaveData\x124\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x18.starve.game.v1.SnapshotR\bsnapshot\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.starve.game.v1.WorldMetaR\x04meta\x12\x18\n" +
	"\ajournal\x18\x03 \x01(\fR\ajournal\x12+\n" +
	"\x03map\x18\x04 \x01(\v2\x19.starve.game.v1.MapConfigR\x03map\x12!\n" +
	"\ftile_effects\x18\x05 \x01(\fR\vtileEffects\x12\x1f\n" +
	"\vtile_params\x18\x06 \x01(\fR\n" +
	"tileParams*\x8d\x01\n" +
	"\bItemKind\x12\x19\n" +
	"\x15ITEM_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fITEM_KIND_BERRY\x10\x01\x12\x12\n" +
	"\x0eITEM_KIND_WOOD\x10\x02\x12\x13\n" +
	"\x0fITEM_KIND_FLINT\x10\x03\x12\x11\n" +
	"\rITEM_KIND_AXE\x10d\x12\x15\n" +
	"\x11ITEM_KIND_PICKAXE\x10e*k\n" +
	"\n" +
	"WorkAction\x12\x1b\n" +
	"\x17WORK_ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10WORK_ACTION_CHOP\x10\x01\x12\x14\n" +
	"\x10WORK_ACTION_MINE\x10\x02\x12\x14\n" +
	"\x10WORK_ACTION_PICK\x10\x03*r\n" +
	"\x0fWorkstationType\x12 \n" +
	"\x1cWORKSTATION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKSTATION_TYPE_CAMPFIRE\x10\x01\x12\x1e\n" +
	"\x1aWORKSTATION_TYPE_WORKBENCH\x10\x02*\x8a\x01\n" +
	"\vEffectOrder\x12\x1c\n" +
	"\x18EFFECT_ORDER_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EFFECT_ORDER_SPEED\x10\x01\x12\x17\n" +
	"\x13EFFECT_ORDER_POISON\x10\x02\x12\x15\n" +
	"\x11EFFECT_ORDER_COLD\x10\x03\x12\x15\n" +
	"\x11EFFECT_ORDER_HEAT\x10\x04*l\n" +
	"\x06Season\x12\x16\n" +
	"\x12SEASON_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEASON_SPRING\x10\x01\x12\x11\n" +
	"\rSEASON_SUMMER\x10\x02\x12\x11\n" +
	"\rSEASON_AUTUMN\x10\x03\x12\x11\n" +
	"\rSEASON_WINTER\x10\x04*\xa0\x01\n" +
	"\vTerrainType\x12\x1c\n" +
	"\x18TERRAIN_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TERRAIN_TYPE_WATER\x10\x01\x12\x15\n" +
	"\x11TERRAIN_TYPE_SAND\x10\x02\x12\x16\n" +
	"\x12TERRAIN_TYPE_GRASS\x10\x03\x12\x15\n" +
	"\x11TERRAIN_TYPE_ROCK\x10\x04\x12\x15\n" +
	"\x11TERRAIN_TYPE_SNOW\x10\x05B\x17Z\x15starve/pkg/proto/gameb\x06proto3"

var (
	file_pkg_proto_game_game_proto_rawDescOnce sync.Once
	file_pkg_proto_game_game_proto_rawDescData []byte
)

func file_pkg_proto_game_game_proto_rawDescGZIP() []byte {
	file_pkg_proto_game_game_proto_rawDescOnce.Do(func() {
		file_pkg_proto_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_game_game_proto_rawDesc), len(file_pkg_proto_game_game_proto_rawDesc)))
	})
	return file_pkg_proto_game_game_proto_rawDescData
}

var file_pkg_proto_game_game_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_pkg_proto_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_pkg_proto_game_game_proto_goTypes = []any{
	(ItemKind)(0),            // 0: starve.game.v1.ItemKind
	(WorkAction)(0),          // 1: starve.game.v1.WorkAction
	(WorkstationType)(0),     // 2: starve.game.v1.WorkstationType
	(EffectOrder)(0),         // 3: starve.game.v1.EffectOrder
	(Season)(0),              // 4: starve.game.v1.Season
	(TerrainType)(0),         // 5: starve.game.v1.TerrainType
	(*Position)(nil),         // 6: starve.game.v1.Position
	(*Moveable)(nil),         // 7: starve.game.v1.Moveable
	(*MoveDir)(nil),          // 8: starve.game.v1.MoveDir
	(*Health)(nil),           // 9: starve.game.v1.Health
	(*Hunger)(nil),           // 10: starve.game.v1.Hunger
	(*Growable)(nil),         // 11: starve.game.v1.Growable
	(*Dead)(nil),             // 12: starve.game.v1.Dead
	(*Player)(nil),           // 13: starve.game.v1.Player
	(*Offline)(nil),          // 14: starve.game.v1.Offline
	(*Workable)(nil),         // 15: starve.game.v1.Workable
	(*Equipped)(nil),         // 16: starve.game.v1.Equipped
	(*Respawn)(nil),          // 17: starve.game.v1.Respawn
	(*Workstation)(nil),      // 18: starve.game.v1.Workstation
	(*Crafting)(nil),         // 19: starve.game.v1.Crafting
	(*EffectInstance)(nil),   // 20: starve.game.v1.EffectInstance
	(*EffectActive)(nil),     // 21: starve.game.v1.EffectActive
	(*Effects)(nil),          // 22: starve.game.v1.Effects
	(*EffectEmitter)(nil),    // 23: starve.game.v1.EffectEmitter
	(*WeatherState)(nil),     // 24: starve.game.v1.WeatherState
	(*Fan)(nil),              // 25: starve.game.v1.Fan
	(*HeatSource)(nil),       // 26: starve.game.v1.HeatSource
	(*WeatherCell)(nil),      // 27: starve.game.v1.WeatherCell
	(*WeatherFrame)(nil),     // 28: starve.game.v1.WeatherFrame
	(*ToolConfig)(nil),       // 29: starve.game.v1.ToolConfig
	(*UseEffectConfig)(nil),  // 30: starve.game.v1.UseEffectConfig
	(*DropConfig)(nil),       // 31: starve.game.v1.DropConfig
	(*TemplateConfig)(nil),   // 32: starve.game.v1.TemplateConfig
	(*ItemRefConfig)(nil),    // 33: starve.game.v1.ItemRefConfig
	(*RecipeConfig)(nil),     // 34: starve.game.v1.RecipeConfig
	(*StationConfig)(nil),    // 35: starve.game.v1.StationConfig
	(*MapConfig)(nil),        // 36: starve.game.v1.MapConfig
	(*GameConfig)(nil),       // 37: starve.game.v1.GameConfig
	(*ItemStack)(nil),        // 38: starve.game.v1.ItemStack
	(*Inventory)(nil),        // 39: starve.game.v1.Inventory
	(*Loot)(nil),             // 40: starve.game.v1.Loot
	(*DayCycle)(nil),         // 41: starve.game.v1.DayCycle
	(*ComponentState)(nil),   // 42: starve.game.v1.ComponentState
	(*EntityState)(nil),      // 43: starve.game.v1.EntityState
	(*RemovedComponent)(nil), // 44: starve.game.v1.RemovedComponent
	(*Snapshot)(nil),         // 45: starve.game.v1.Snapshot
	(*SnapshotDelta)(nil),    // 46: starve.game.v1.SnapshotDelta
	(*WorldMeta)(nil),        // 47: starve.game.v1.WorldMeta
	(*SaveData)(nil),         // 48: starve.game.v1.SaveData
}
var file_pkg_proto_game_game_proto_depIdxs = []int32{
	8,  // 0: starve.game.v1.Moveable.queue:type_name -> starve.game.v1.MoveDir
	0,  // 1: starve.game.v1.Workable.kind:type_name -> starve.game.v1.ItemKind
	1,  // 2: starve.game.v1.Workable.action:type_name -> starve.game.v1.WorkAction
	0,  // 3: starve.game.v1.Equipped.kind:type_name -> starve.game.v1.ItemKind
	2,  // 4: starve.game.v1.Workstation.type:type_name -> starve.game.v1.WorkstationType
	38, // 5: starve.game.v1.Crafting.ingredients:type_name -> starve.game.v1.ItemStack
	3,  // 6: starve.game.v1.EffectInstance.order:type_name -> starve.game.v1.EffectOrder
	3,  // 7: starve.game.v1.EffectActive.order:type_name -> starve.game.v1.EffectOrder
	21, // 8: starve.game.v1.Effects.active:type_name -> starve.game.v1.EffectActive
	20, // 9: starve.game.v1.EffectEmitter.effects:type_name -> starve.game.v1.EffectInstance
	4,  // 10: starve.game.v1.WeatherState.season:type_name -> starve.game.v1.Season
	4,  // 11: starve.game.v1.WeatherFrame.season:type_name -> starve.game.v1.Season
	27, // 12: starve.game.v1.WeatherFrame.cells:type_name -> starve.game.v1.WeatherCell
	1,  // 13: starve.game.v1.ToolConfig.action:type_name -> starve.game.v1.WorkAction
	0,  // 14: starve.game.v1.DropConfig.kind:type_name -> starve.game.v1.ItemKind
	0,  // 15: starve.game.v1.TemplateConfig.kind:type_name -> starve.game.v1.ItemKind
	29, // 16: starve.game.v1.TemplateConfig.tool:type_name -> starve.game.v1.ToolConfig
	30, // 17: starve.game.v1.TemplateConfig.use_effect:type_name -> starve.game.v1.UseEffectConfig
	31, // 18: starve.game.v1.TemplateConfig.drop_table:type_name -> starve.game.v1.DropConfig
	0,  // 19: starve.game.v1.ItemRefConfig.kind:type_name -> starve.game.v1.ItemKind
	2,  // 20: starve.game.v1.RecipeConfig.workstation:type_name -> starve.game.v1.WorkstationType
	33, // 21: starve.game.v1.RecipeConfig.output:type_name -> starve.game.v1.ItemRefConfig
	33, // 22: starve.game.v1.RecipeConfig.ingredients:type_name -> starve.game.v1.ItemRefConfig
	2,  // 23: starve.game.v1.StationConfig.type:type_name -> starve.game.v1.WorkstationType
	32, // 24: starve.game.v1.GameConfig.templates:type_name -> starve.game.v1.TemplateConfig
	34, // 25: starve.game.v1.GameConfig.recipes:type_name -> starve.game.v1.RecipeConfig
	35, // 26: starve.game.v1.GameConfig.stations:type_name -> starve.game.v1.StationConfig
	36, // 27: starve.game.v1.GameConfig.map:type_name -> starve.game.v1.MapConfig
	0,  // 28: starve.game.v1.ItemStack.kind:type_name -> starve.game.v1.ItemKind
	38, // 29: starve.game.v1.Inventory.items:type_name -> starve.game.v1.ItemStack
	38, // 30: starve.game.v1.Loot.items:type_name -> starve.game.v1.ItemStack
	42, // 31: starve.game.v1.EntityState.components:type_name -> starve.game.v1.ComponentState
	43, // 32: starve.game.v1.Snapshot.entities:type_name -> starve.game.v1.EntityState
	41, // 33: starve.game.v1.Snapshot.day_cycle:type_name -> starve.game.v1.DayCycle
	24, // 34: starve.game.v1.Snapshot.weather:type_name -> starve.game.v1.WeatherState
	43, // 35: starve.game.v1.SnapshotDelta.entities:type_name -> starve.game.v1.EntityState
	41, // 36: starve.game.v1.SnapshotDelta.day_cycle:type_name -> starve.game.v1.DayCycle
	44, // 37: starve.game.v1.SnapshotDelta.removed_components:type_name -> starve.game.v1.RemovedComponent
	24, // 38: starve.game.v1.SnapshotDelta.weather:type_name -> starve.game.v1.WeatherState
	45, // 39: starve.game.v1.SaveData.snapshot:type_name -> starve.game.v1.Snapshot
	47, // 40: starve.game.v1.SaveData.meta:type_name -> starve.game.v1.WorldMeta
	36, // 41: starve.game.v1.SaveData.map:type_name -> starve.game.v1.MapConfig
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_pkg_proto_game_game_proto_init() }
func file_pkg_proto_game_game_proto_init() {
	if File_pkg_proto_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_game_game_proto_rawDesc), len(file_pkg_proto_game_game_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_game_game_proto_goTypes,
		DependencyIndexes: file_pkg_proto_game_game_proto_depIdxs,
		EnumInfos:         file_pkg_proto_game_game_proto_enumTypes,
		MessageInfos:      file_pkg_proto_game_game_proto_msgTypes,
	}.Build()
	File_pkg_proto_game_game_proto = out.File
	file_pkg_proto_game_game_proto_goTypes = nil
	file_pkg_proto_game_game_proto_depIdxs = nil
}
