// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginRequest 客户端登录请求（route="gate.login"，request）。
// 握手完成后第一个业务消息；token 由 starve 账号服务签发（复用 feeds 的 bcrypt+JWT 方案）。
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LoginResponse 登录响应：成功返回玩家在世界中的实体 ID。
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityId      uint64                 `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 玩家在世界中的实体 ID（服务器分配，客户端后续命令引用）
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PlayerMove 移动指令（route="world.player.move"，notify，fire-and-forget）。
// 目标实体由服务器从会话表得出，客户端不传实体 ID。
type PlayerMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dx            int32                  `protobuf:"varint,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,2,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerMove) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *PlayerMove) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

// PlayerGather 采集指令（route="world.player.gather"，notify）。
// 目标实体 ID 由客户端从快照选取（带 Gatherable 组件的实体）。
type PlayerGather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEntity  uint64                 `protobuf:"varint,1,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGather) Reset() {
	*x = PlayerGather{}
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGather) ProtoMessage() {}

func (x *PlayerGather) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGather.ProtoReflect.Descriptor instead.
func (*PlayerGather) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerGather) GetTargetEntity() uint64 {
	if x != nil {
		return x.TargetEntity
	}
	return 0
}

// PlayerAttack 攻击指令（route="world.player.attack"，notify）。
// 攻击者 = 登录会话绑定的实体；目标实体 ID 由客户端从快照选取。
type PlayerAttack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEntity  uint64                 `protobuf:"varint,1,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAttack) Reset() {
	*x = PlayerAttack{}
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAttack) ProtoMessage() {}

func (x *PlayerAttack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAttack.ProtoReflect.Descriptor instead.
func (*PlayerAttack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerAttack) GetTargetEntity() uint64 {
	if x != nil {
		return x.TargetEntity
	}
	return 0
}

// SaveRequest 客户端点存档（route="game.save"，request，无 body）。
// SaveResponse 存档结果。
type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *SaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// MovePush 位置推送（route="world.player.move"，push，服务器→客户端）。
type MovePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePush) Reset() {
	*x = MovePush{}
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePush) ProtoMessage() {}

func (x *MovePush) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePush.ProtoReflect.Descriptor instead.
func (*MovePush) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *MovePush) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *MovePush) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MovePush) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_pkg_proto_message_proto protoreflect.FileDescriptor

const file_pkg_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/message.proto\x12\x0fstarve.proto.v1\"$\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"y\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x04R\bentityId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\n" +
	"PlayerMove\x12\x0e\n" +
	"\x02dx\x18\x01 \x01(\x05R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x02 \x01(\x05R\x02dy\"3\n" +
	"\fPlayerGather\x12#\n" +
	"\rtarget_entity\x18\x01 \x01(\x04R\ftargetEntity\"3\n" +
	"\fPlayerAttack\x12#\n" +
	"\rtarget_entity\x18\x01 \x01(\x04R\ftargetEntity\"(\n" +
	"\fSaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\bMovePush\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01yB\x12Z\x10starve/pkg/protob\x06proto3"

var (
	file_pkg_proto_message_proto_rawDescOnce sync.Once
	file_pkg_proto_message_proto_rawDescData []byte
)

func file_pkg_proto_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)))
	})
	return file_pkg_proto_message_proto_rawDescData
}

var file_pkg_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_message_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: starve.proto.v1.LoginRequest
	(*LoginResponse)(nil), // 1: starve.proto.v1.LoginResponse
	(*PlayerMove)(nil),    // 2: starve.proto.v1.PlayerMove
	(*PlayerGather)(nil),  // 3: starve.proto.v1.PlayerGather
	(*PlayerAttack)(nil),  // 4: starve.proto.v1.PlayerAttack
	(*SaveResponse)(nil),  // 5: starve.proto.v1.SaveResponse
	(*MovePush)(nil),      // 6: starve.proto.v1.MovePush
}
var file_pkg_proto_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_message_proto_init() }
func file_pkg_proto_message_proto_init() {
	if File_pkg_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_message_proto = out.File
	file_pkg_proto_message_proto_goTypes = nil
	file_pkg_proto_message_proto_depIdxs = nil
}
