// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginRequest 客户端登录请求（route="gate.login"，request）。
// 握手完成后第一个业务消息；token 由 starve 账号服务签发（复用 feeds 的 bcrypt+JWT 方案）。
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LoginResponse 登录响应：成功返回玩家在世界中的实体 ID。
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityId      uint64                 `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // 玩家在世界中的实体 ID（服务器分配，客户端后续命令引用）
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PlayerMove 移动指令（route="world.player.move"，notify，fire-and-forget）。
// 目标实体由服务器从会话表得出，客户端不传实体 ID。
type PlayerMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dx            int32                  `protobuf:"varint,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,2,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMove) Reset() {
	*x = PlayerMove{}
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMove) ProtoMessage() {}

func (x *PlayerMove) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMove.ProtoReflect.Descriptor instead.
func (*PlayerMove) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerMove) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *PlayerMove) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

// PlayerGather 采集指令（route="world.player.gather"，notify）。
// 目标实体 ID 由客户端从快照选取（带 Gatherable 组件的实体）。
type PlayerGather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEntity  uint64                 `protobuf:"varint,1,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGather) Reset() {
	*x = PlayerGather{}
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGather) ProtoMessage() {}

func (x *PlayerGather) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGather.ProtoReflect.Descriptor instead.
func (*PlayerGather) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerGather) GetTargetEntity() uint64 {
	if x != nil {
		return x.TargetEntity
	}
	return 0
}

// PlayerAttack 攻击指令（route="world.player.attack"，notify）。
// 攻击者 = 登录会话绑定的实体；目标实体 ID 由客户端从快照选取。
type PlayerAttack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEntity  uint64                 `protobuf:"varint,1,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAttack) Reset() {
	*x = PlayerAttack{}
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAttack) ProtoMessage() {}

func (x *PlayerAttack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAttack.ProtoReflect.Descriptor instead.
func (*PlayerAttack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerAttack) GetTargetEntity() uint64 {
	if x != nil {
		return x.TargetEntity
	}
	return 0
}

// PlayerPickup 拾取指令（route="world.player.pickup"，notify）。
// 目标 = 带 Loot 组件的掉落物实体。
type PlayerPickup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LootEntity    uint64                 `protobuf:"varint,1,opt,name=loot_entity,json=lootEntity,proto3" json:"loot_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPickup) Reset() {
	*x = PlayerPickup{}
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPickup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPickup) ProtoMessage() {}

func (x *PlayerPickup) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPickup.ProtoReflect.Descriptor instead.
func (*PlayerPickup) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerPickup) GetLootEntity() uint64 {
	if x != nil {
		return x.LootEntity
	}
	return 0
}

// PlayerUse 使用指令（route="world.player.use"，notify）。
// kind 为 ItemKind 枚举值（见 game.proto），从自己背包消耗一个并应用模板 use_effect。
type PlayerUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUse) Reset() {
	*x = PlayerUse{}
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUse) ProtoMessage() {}

func (x *PlayerUse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUse.ProtoReflect.Descriptor instead.
func (*PlayerUse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerUse) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

// PlayerEquip 装备工具（route="world.player.equip"，notify）。
// kind = ItemKind 枚举值；0 = 卸下（徒手）。
type PlayerEquip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEquip) Reset() {
	*x = PlayerEquip{}
	mi := &file_pkg_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEquip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEquip) ProtoMessage() {}

func (x *PlayerEquip) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEquip.ProtoReflect.Descriptor instead.
func (*PlayerEquip) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerEquip) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

// PlayerChop 砍伐（route="world.player.chop"，notify）。目标 = Workable{CHOP}。
type PlayerChop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEntity  uint64                 `protobuf:"varint,1,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerChop) Reset() {
	*x = PlayerChop{}
	mi := &file_pkg_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerChop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerChop) ProtoMessage() {}

func (x *PlayerChop) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerChop.ProtoReflect.Descriptor instead.
func (*PlayerChop) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerChop) GetTargetEntity() uint64 {
	if x != nil {
		return x.TargetEntity
	}
	return 0
}

// PlayerMine 挖掘（route="world.player.mine"，notify）。目标 = Workable{MINE}。
type PlayerMine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEntity  uint64                 `protobuf:"varint,1,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerMine) Reset() {
	*x = PlayerMine{}
	mi := &file_pkg_proto_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerMine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMine) ProtoMessage() {}

func (x *PlayerMine) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMine.ProtoReflect.Descriptor instead.
func (*PlayerMine) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerMine) GetTargetEntity() uint64 {
	if x != nil {
		return x.TargetEntity
	}
	return 0
}

// PlayerDrop 丢弃背包物品（route="world.player.drop"，notify）。
// 从自己背包移除 count 个 kind 物品，在当前位置生成可拾取的掉落物。
type PlayerDrop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDrop) Reset() {
	*x = PlayerDrop{}
	mi := &file_pkg_proto_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDrop) ProtoMessage() {}

func (x *PlayerDrop) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDrop.ProtoReflect.Descriptor instead.
func (*PlayerDrop) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerDrop) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *PlayerDrop) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// PlayerCraft 制作请求（route="world.player.craft"，request）。
// 服务端校验配方/材料/工作站后返回 CraftResponse（started + 制作时长），
// 制作完成时服务端推送 world.craft.done。
type PlayerCraft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCraft) Reset() {
	*x = PlayerCraft{}
	mi := &file_pkg_proto_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCraft) ProtoMessage() {}

func (x *PlayerCraft) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCraft.ProtoReflect.Descriptor instead.
func (*PlayerCraft) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerCraft) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

// Build 建造请求（route="world.build"，request）：只创建未放置的建筑实体（kind）。
// 执行者不限于玩家（Boss/角色等也可），网关填入当前会话实体。
// 响应 BuildResponse 携带新建实体 id（后续 Place / BuildCheck 引用）。
type Build struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_pkg_proto_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{12}
}

func (x *Build) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

// BuildResponse 建造请求的响应：ok=true 时 entity 为新建（未放置）建筑实体；
// ok=false 时 message 携带失败原因（player dead / unknown kind 等）。
type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Entity        uint64                 `protobuf:"varint,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{13}
}

func (x *BuildResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BuildResponse) GetEntity() uint64 {
	if x != nil {
		return x.Entity
	}
	return 0
}

func (x *BuildResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Place 放置指令（route="world.place"，notify）：把已创建的建筑放到坐标。
type Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        uint64                 `protobuf:"varint,1,opt,name=entity,proto3" json:"entity,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_pkg_proto_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{14}
}

func (x *Place) GetEntity() uint64 {
	if x != nil {
		return x.Entity
	}
	return 0
}

func (x *Place) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Place) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// BuildCheck 建造可放置查询（route="world.build.check"，request）：返回 ok。
type BuildCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        uint64                 `protobuf:"varint,1,opt,name=entity,proto3" json:"entity,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCheck) Reset() {
	*x = BuildCheck{}
	mi := &file_pkg_proto_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCheck) ProtoMessage() {}

func (x *BuildCheck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCheck.ProtoReflect.Descriptor instead.
func (*BuildCheck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{15}
}

func (x *BuildCheck) GetEntity() uint64 {
	if x != nil {
		return x.Entity
	}
	return 0
}

func (x *BuildCheck) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BuildCheck) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type BuildCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCheckResponse) Reset() {
	*x = BuildCheckResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCheckResponse) ProtoMessage() {}

func (x *BuildCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCheckResponse.ProtoReflect.Descriptor instead.
func (*BuildCheckResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{16}
}

func (x *BuildCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Demolish 拆除指令（route="world.demolish"，notify）：目标建筑实体。
type Demolish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetEntity  uint64                 `protobuf:"varint,1,opt,name=target_entity,json=targetEntity,proto3" json:"target_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demolish) Reset() {
	*x = Demolish{}
	mi := &file_pkg_proto_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demolish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demolish) ProtoMessage() {}

func (x *Demolish) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demolish.ProtoReflect.Descriptor instead.
func (*Demolish) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{17}
}

func (x *Demolish) GetTargetEntity() uint64 {
	if x != nil {
		return x.TargetEntity
	}
	return 0
}

// CraftResponse 制作请求的响应：
// started=true 表示已开始（材料已扣），ticks 为制作时长；
// started=false 时 message 携带失败原因（unknown recipe / insufficient materials / need workstation...）。
type CraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Ticks         int32                  `protobuf:"varint,3,opt,name=ticks,proto3" json:"ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CraftResponse) Reset() {
	*x = CraftResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftResponse) ProtoMessage() {}

func (x *CraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftResponse.ProtoReflect.Descriptor instead.
func (*CraftResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{18}
}

func (x *CraftResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *CraftResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CraftResponse) GetTicks() int32 {
	if x != nil {
		return x.Ticks
	}
	return 0
}

// CraftDone 制作完成推送（服务端 → 客户端，广播，客户端按 uid 过滤）。
type CraftDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RecipeId      string                 `protobuf:"bytes,2,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CraftDone) Reset() {
	*x = CraftDone{}
	mi := &file_pkg_proto_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CraftDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CraftDone) ProtoMessage() {}

func (x *CraftDone) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CraftDone.ProtoReflect.Descriptor instead.
func (*CraftDone) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{19}
}

func (x *CraftDone) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CraftDone) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *CraftDone) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// PlayerCancelCraft 主动取消制作（route="world.player.craft.cancel"，notify）。
// 客户端主动打断（如制作中开始走动）；服务端移除 Crafting、退回材料并推送取消。
type PlayerCancelCraft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerCancelCraft) Reset() {
	*x = PlayerCancelCraft{}
	mi := &file_pkg_proto_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerCancelCraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerCancelCraft) ProtoMessage() {}

func (x *PlayerCancelCraft) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerCancelCraft.ProtoReflect.Descriptor instead.
func (*PlayerCancelCraft) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{20}
}

// PlayerSplit 拆分背包物品（route="world.player.split"，notify）。
// 从 from_slot 槽取出 count 个放入第一个空槽（堆叠上限/耐久随物品）。
type PlayerSplit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromSlot      int32                  `protobuf:"varint,1,opt,name=from_slot,json=fromSlot,proto3" json:"from_slot,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSplit) Reset() {
	*x = PlayerSplit{}
	mi := &file_pkg_proto_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSplit) ProtoMessage() {}

func (x *PlayerSplit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSplit.ProtoReflect.Descriptor instead.
func (*PlayerSplit) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerSplit) GetFromSlot() int32 {
	if x != nil {
		return x.FromSlot
	}
	return 0
}

func (x *PlayerSplit) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// SaveRequest 客户端点存档（route="game.save"，request，无 body）。
// SaveResponse 存档结果。
type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_pkg_proto_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{22}
}

func (x *SaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// MovePush 位置推送（route="world.player.move"，push，服务器→客户端）。
type MovePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePush) Reset() {
	*x = MovePush{}
	mi := &file_pkg_proto_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePush) ProtoMessage() {}

func (x *MovePush) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePush.ProtoReflect.Descriptor instead.
func (*MovePush) Descriptor() ([]byte, []int) {
	return file_pkg_proto_message_proto_rawDescGZIP(), []int{23}
}

func (x *MovePush) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *MovePush) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MovePush) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_pkg_proto_message_proto protoreflect.FileDescriptor

const file_pkg_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/message.proto\x12\x0fstarve.proto.v1\"$\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"y\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\x04R\bentityId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\n" +
	"PlayerMove\x12\x0e\n" +
	"\x02dx\x18\x01 \x01(\x05R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x02 \x01(\x05R\x02dy\"3\n" +
	"\fPlayerGather\x12#\n" +
	"\rtarget_entity\x18\x01 \x01(\x04R\ftargetEntity\"3\n" +
	"\fPlayerAttack\x12#\n" +
	"\rtarget_entity\x18\x01 \x01(\x04R\ftargetEntity\"/\n" +
	"\fPlayerPickup\x12\x1f\n" +
	"\vloot_entity\x18\x01 \x01(\x04R\n" +
	"lootEntity\"\x1f\n" +
	"\tPlayerUse\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\"!\n" +
	"\vPlayerEquip\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\"1\n" +
	"\n" +
	"PlayerChop\x12#\n" +
	"\rtarget_entity\x18\x01 \x01(\x04R\ftargetEntity\"1\n" +
	"\n" +
	"PlayerMine\x12#\n" +
	"\rtarget_entity\x18\x01 \x01(\x04R\ftargetEntity\"6\n" +
	"\n" +
	"PlayerDrop\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"*\n" +
	"\vPlayerCraft\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\tR\brecipeId\"\x1b\n" +
	"\x05Build\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\"Q\n" +
	"\rBuildResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\x04R\x06entity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\";\n" +
	"\x05Place\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\x04R\x06entity\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"@\n" +
	"\n" +
	"BuildCheck\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\x04R\x06entity\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"$\n" +
	"\x12BuildCheckResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"/\n" +
	"\bDemolish\x12#\n" +
	"\rtarget_entity\x18\x01 \x01(\x04R\ftargetEntity\"Y\n" +
	"\rCraftResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05ticks\x18\x03 \x01(\x05R\x05ticks\"T\n" +
	"\tCraftDone\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1b\n" +
	"\trecipe_id\x18\x02 \x01(\tR\brecipeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x13\n" +
	"\x11PlayerCancelCraft\"@\n" +
	"\vPlayerSplit\x12\x1b\n" +
	"\tfrom_slot\x18\x01 \x01(\x05R\bfromSlot\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"(\n" +
	"\fSaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"C\n" +
	"\bMovePush\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01yB\x12Z\x10starve/pkg/protob\x06proto3"

var (
	file_pkg_proto_message_proto_rawDescOnce sync.Once
	file_pkg_proto_message_proto_rawDescData []byte
)

func file_pkg_proto_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)))
	})
	return file_pkg_proto_message_proto_rawDescData
}

var file_pkg_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_pkg_proto_message_proto_goTypes = []any{
	(*LoginRequest)(nil),       // 0: starve.proto.v1.LoginRequest
	(*LoginResponse)(nil),      // 1: starve.proto.v1.LoginResponse
	(*PlayerMove)(nil),         // 2: starve.proto.v1.PlayerMove
	(*PlayerGather)(nil),       // 3: starve.proto.v1.PlayerGather
	(*PlayerAttack)(nil),       // 4: starve.proto.v1.PlayerAttack
	(*PlayerPickup)(nil),       // 5: starve.proto.v1.PlayerPickup
	(*PlayerUse)(nil),          // 6: starve.proto.v1.PlayerUse
	(*PlayerEquip)(nil),        // 7: starve.proto.v1.PlayerEquip
	(*PlayerChop)(nil),         // 8: starve.proto.v1.PlayerChop
	(*PlayerMine)(nil),         // 9: starve.proto.v1.PlayerMine
	(*PlayerDrop)(nil),         // 10: starve.proto.v1.PlayerDrop
	(*PlayerCraft)(nil),        // 11: starve.proto.v1.PlayerCraft
	(*Build)(nil),              // 12: starve.proto.v1.Build
	(*BuildResponse)(nil),      // 13: starve.proto.v1.BuildResponse
	(*Place)(nil),              // 14: starve.proto.v1.Place
	(*BuildCheck)(nil),         // 15: starve.proto.v1.BuildCheck
	(*BuildCheckResponse)(nil), // 16: starve.proto.v1.BuildCheckResponse
	(*Demolish)(nil),           // 17: starve.proto.v1.Demolish
	(*CraftResponse)(nil),      // 18: starve.proto.v1.CraftResponse
	(*CraftDone)(nil),          // 19: starve.proto.v1.CraftDone
	(*PlayerCancelCraft)(nil),  // 20: starve.proto.v1.PlayerCancelCraft
	(*PlayerSplit)(nil),        // 21: starve.proto.v1.PlayerSplit
	(*SaveResponse)(nil),       // 22: starve.proto.v1.SaveResponse
	(*MovePush)(nil),           // 23: starve.proto.v1.MovePush
}
var file_pkg_proto_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_message_proto_init() }
func file_pkg_proto_message_proto_init() {
	if File_pkg_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_message_proto_rawDesc), len(file_pkg_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_message_proto = out.File
	file_pkg_proto_message_proto_goTypes = nil
	file_pkg_proto_message_proto_depIdxs = nil
}
